"""Hindi catalog: Devanagari titles from live Booknomics saransh + classics seed."""

from __future__ import annotations

import re
from pathlib import Path
from urllib.parse import unquote

from extra_slugs import guess_category

HERE = Path(__file__).resolve().parent

# (title_hi, author_hi, category, ascii_slug)
HINDI_SEED: list[tuple[str, str, str, str]] = [
    ("गोदान", "मुंशी प्रेमचंद", "हिन्दी साहित्य", "godan"),
    ("गबन", "मुंशी प्रेमचंद", "हिन्दी साहित्य", "gaban"),
    ("सेवासदन", "मुंशी प्रेमचंद", "हिन्दी साहित्य", "sevasadan"),
    ("निर्मला", "मुंशी प्रेमचंद", "हिन्दी साहित्य", "nirmala"),
    ("रंगभूमि", "मुंशी प्रेमचंद", "हिन्दी साहित्य", "rangbhoomi"),
    ("कर्मभूमि", "मुंशी प्रेमचंद", "हिन्दी साहित्य", "karmabhoomi"),
    ("प्रेमाश्रम", "मुंशी प्रेमचंद", "हिन्दी साहित्य", "premashram"),
    ("कायाकल्प", "मुंशी प्रेमचंद", "हिन्दी साहित्य", "kayakalp"),
    ("मानसरोवर", "मुंशी प्रेमचंद", "हिन्दी साहित्य", "mansarovar"),
    ("बूढ़ी काकी", "मुंशी प्रेमचंद", "हिन्दी साहित्य", "burhi-kaki"),
    ("कफन", "मुंशी प्रेमचंद", "हिन्दी साहित्य", "kafan"),
    ("पूस की रात", "मुंशी प्रेमचंद", "हिन्दी साहित्य", "poos-ki-raat"),
    ("ईदगाह", "मुंशी प्रेमचंद", "हिन्दी साहित्य", "idgah"),
    ("शतरंज के खिलाड़ी", "मुंशी प्रेमचंद", "हिन्दी साहित्य", "shatranj-ke-khiladi"),
    ("ठाकुर का कुआँ", "मुंशी प्रेमचंद", "हिन्दी साहित्य", "thakur-ka-kuan"),
    ("सद्गति", "मुंशी प्रेमचंद", "हिन्दी साहित्य", "sadgati"),
    ("मधुशाला", "हरिवंश राय बच्चन", "हिन्दी साहित्य", "madhushala"),
    ("मधुबाला", "हरिवंश राय बच्चन", "हिन्दी साहित्य", "madhubala"),
    ("मधुकलश", "हरिवंश राय बच्चन", "हिन्दी साहित्य", "madhukalash"),
    ("निशा निमंत्रण", "हरिवंश राय बच्चन", "हिन्दी साहित्य", "nisha-nimantran"),
    ("आत्मकथा की चार खण्ड", "हरिवंश राय बच्चन", "जीवनी", "bachchan-atmakatha"),
    ("कामायनी", "जयशंकर प्रसाद", "हिन्दी साहित्य", "kamayani"),
    ("आँसू", "जयशंकर प्रसाद", "हिन्दी साहित्य", "aansu"),
    ("लहर", "जयशंकर प्रसाद", "हिन्दी साहित्य", "lahar"),
    ("झरना", "जयशंकर प्रसाद", "हिन्दी साहित्य", "jharna"),
    ("कामायनी रहस्य", "जयशंकर प्रसाद", "हिन्दी साहित्य", "kamayani-rahasya"),
    ("चन्द्रगुप्त", "जयशंकर प्रसाद", "हिन्दी साहित्य", "chandragupta"),
    ("स्कंदगुप्त", "जयशंकर प्रसाद", "हिन्दी साहित्य", "skandagupta"),
    ("ध्रुवस्वामिनी", "जयशंकर प्रसाद", "हिन्दी साहित्य", "dhruvaswamini"),
    ("अजातशत्रु", "जयशंकर प्रसाद", "हिन्दी साहित्य", "ajatshatru-prasad"),
    ("तितली", "जयशंकर प्रसाद", "हिन्दी साहित्य", "titli"),
    ("कंकाल", "जयशंकर प्रसाद", "हिन्दी साहित्य", "kankal"),
    ("इरावती", "जयशंकर प्रसाद", "हिन्दी साहित्य", "iravati"),
    ("रश्मिरथी", "रामधारी सिंह दिनकर", "हिन्दी साहित्य", "rashmirathi"),
    ("कुरुक्षेत्र", "रामधारी सिंह दिनकर", "हिन्दी साहित्य", "kurukshetra"),
    ("उर्वशी", "रामधारी सिंह दिनकर", "हिन्दी साहित्य", "urvashi"),
    ("परशुराम की प्रतीक्षा", "रामधारी सिंह दिनकर", "हिन्दी साहित्य", "parshuram-ki-pratiksha"),
    ("हुंकार", "रामधारी सिंह दिनकर", "हिन्दी साहित्य", "hunkar"),
    ("मिट्टी की ओर", "रामधारी सिंह दिनकर", "हिन्दी साहित्य", "mitti-ki-or"),
    ("संस्कृति के चार अध्याय", "रामधारी सिंह दिनकर", "इतिहास", "sanskriti-ke-char-adhyay"),
    ("राम की शक्ति पूजा", "सूर्यकांत त्रिपाठी निराला", "हिन्दी साहित्य", "ram-ki-shakti-pooja"),
    ("सरोज स्मृति", "सूर्यकांत त्रिपाठी निराला", "हिन्दी साहित्य", "saroj-smriti"),
    ("तुलसीदास", "सूर्यकांत त्रिपाठी निराला", "हिन्दी साहित्य", "tulsidas-nirala"),
    ("परिमल", "सूर्यकांत त्रिपाठी निराला", "हिन्दी साहित्य", "parimal"),
    ("अनामिका", "सूर्यकांत त्रिपाठी निराला", "हिन्दी साहित्य", "anamika"),
    ("गीतिका", "सूर्यकांत त्रिपाठी निराला", "हिन्दी साहित्य", "geetika"),
    ("पल्लव", "सुमित्रानंदन पंत", "हिन्दी साहित्य", "pallav"),
    ("वीणा", "सुमित्रानंदन पंत", "हिन्दी साहित्य", "veena"),
    ("ग्राम्या", "सुमित्रानंदन पंत", "हिन्दी साहित्य", "gramya"),
    ("युगवाणी", "सुमित्रानंदन पंत", "हिन्दी साहित्य", "yugvani"),
    ("गुंजन", "सुमित्रानंदन पंत", "हिन्दी साहित्य", "gunjan"),
    ("स्वर्णकिरण", "सुमित्रानंदन पंत", "हिन्दी साहित्य", "swarnakiran"),
    ("यामा", "महादेवी वर्मा", "हिन्दी साहित्य", "yama"),
    ("नीहार", "महादेवी वर्मा", "हिन्दी साहित्य", "nihar"),
    ("रश्मि", "महादेवी वर्मा", "हिन्दी साहित्य", "rashmi"),
    ("नीरजा", "महादेवी वर्मा", "हिन्दी साहित्य", "neerja"),
    ("सांध्यगीत", "महादेवी वर्मा", "हिन्दी साहित्य", "sandhyageet"),
    ("श्रृंखला की कड़ियाँ", "महादेवी वर्मा", "हिन्दी साहित्य", "shrinkhala-ki-kadiyan"),
    ("स्मृति चित्र", "महादेवी वर्मा", "जीवनी", "smriti-chitra"),
    ("पथ के साथी", "महादेवी वर्मा", "जीवनी", "path-ke-sathi"),
    ("मेरा परिवार", "महादेवी वर्मा", "जीवनी", "mera-parivar"),
    ("साकेत", "मैथिलीशरण गुप्त", "हिन्दी साहित्य", "saket"),
    ("भारत-भारती", "मैथिलीशरण गुप्त", "हिन्दी साहित्य", "bharat-bharati"),
    ("यशोधरा", "मैथिलीशरण गुप्त", "हिन्दी साहित्य", "yashodhara"),
    ("जयद्रथ वध", "मैथिलीशरण गुप्त", "हिन्दी साहित्य", "jayadrath-vadh"),
    ("शेखर: एक जीवनी", "सच्चिदानंद हीरानंद वात्स्यायन अज्ञेय", "हिन्दी साहित्य", "shekhar-ek-jivani"),
    ("नदी के द्वीप", "अज्ञेय", "हिन्दी साहित्य", "nadi-ke-dweep"),
    ("अपने अपने अजनबी", "अज्ञेय", "हिन्दी साहित्य", "apne-apne-ajnabee"),
    ("आँगन के पार द्वार", "अज्ञेय", "हिन्दी साहित्य", "angan-ke-paar-dwar"),
    ("आत्मनेपद", "अज्ञेय", "हिन्दी साहित्य", "atmanepad"),
    ("अरे यायावर रहेगा याद", "अज्ञेय", "हिन्दी साहित्य", "are-yayavar-rahega-yaad"),
    ("बावरा अहेरी", "अज्ञेय", "हिन्दी साहित्य", "bawra-aheri"),
    ("गुनाहों का देवता", "धर्मवीर भारती", "हिन्दी साहित्य", "gunahon-ka-devta"),
    ("सूरज का सातवाँ घोड़ा", "धर्मवीर भारती", "हिन्दी साहित्य", "suraj-ka-saatvan-ghora"),
    ("अंधायुग", "धर्मवीर भारती", "हिन्दी साहित्य", "andhayug"),
    ("ठंडा लोहा", "धर्मवीर भारती", "हिन्दी साहित्य", "thanda-loha"),
    ("सपना अभी बाकी है", "धर्मवीर भारती", "हिन्दी साहित्य", "sapna-abhi-baaki-hai"),
    ("मैला आंचल", "फणीश्वरनाथ रेणु", "हिन्दी साहित्य", "maila-aanchal"),
    ("परती परिकथा", "फणीश्वरनाथ रेणु", "हिन्दी साहित्य", "parti-parikatha"),
    ("तीसरी कसम", "फणीश्वरनाथ रेणु", "हिन्दी साहित्य", "teesri-kasam"),
    ("राग दरबारी", "श्रीलाल शुक्ल", "हिन्दी साहित्य", "raag-darbari"),
    ("अज्ञातवास", "श्रीलाल शुक्ल", "हिन्दी साहित्य", "agyatvas"),
    ("झूठा सच", "यशपाल", "हिन्दी साहित्य", "jhootha-sach"),
    ("दिव्या", "यशपाल", "हिन्दी साहित्य", "divya"),
    ("दादा कॉमरेड", "यशपाल", "हिन्दी साहित्य", "dada-comrade"),
    ("अमिता", "यशपाल", "हिन्दी साहित्य", "amita"),
    ("घेरे के बाहर", "यशपाल", "हिन्दी साहित्य", "ghere-ke-bahar"),
    ("अपना अपना भाग्य", "यशपाल", "हिन्दी साहित्य", "apna-apna-bhagya"),
    ("तमस", "भीष्म साहनी", "हिन्दी साहित्य", "tamas"),
    ("बसंती", "भीष्म साहनी", "हिन्दी साहित्य", "basanti"),
    ("मधवी", "भीष्म साहनी", "हिन्दी साहित्य", "madhavi"),
    ("हानूश", "भीष्म साहनी", "हिन्दी साहित्य", "hanush"),
    ("मायाराम सुराना", "भीष्म साहनी", "हिन्दी साहित्य", "mayaram-surana"),
    ("आषाढ़ का एक दिन", "मोहन राकेश", "हिन्दी साहित्य", "ashadh-ka-ek-din"),
    ("आधे-अधूरे", "मोहन राकेश", "हिन्दी साहित्य", "aadhe-adhure"),
    ("लहरों के राजहंस", "मोहन राकेश", "हिन्दी साहित्य", "lahron-ke-rajhans"),
    ("पहचान", "मोहन राकेश", "हिन्दी साहित्य", "pehchan"),
    ("आपका बंटी", "मन्नू भंडारी", "हिन्दी साहित्य", "aapka-banti"),
    ("यही सच है", "मन्नू भंडारी", "हिन्दी साहित्य", "yahi-sach-hai"),
    ("महाभोज", "मन्नू भंडारी", "हिन्दी साहित्य", "mahabhoj"),
    ("एक प्लेट सैलाब", "मन्नू भंडारी", "हिन्दी साहित्य", "ek-plate-sailab"),
    ("मित्रो मरजानी", "कृष्णा सोबती", "हिन्दी साहित्य", "mitro-marjani"),
    ("ज़िंदगीनामा", "कृष्णा सोबती", "हिन्दी साहित्य", "zindaginama"),
    ("डार से बिछुड़ी", "कृष्णा सोबती", "हिन्दी साहित्य", "dar-se-bichhudi"),
    ("समय सरगम", "कृष्णा सोबती", "हिन्दी साहित्य", "samay-sargam"),
    ("ऐ लड़की", "कृष्णा सोबती", "हिन्दी साहित्य", "ae-ladki"),
    ("परिंदे", "निर्मल वर्मा", "हिन्दी साहित्य", "parinde"),
    ("वे दिन", "निर्मल वर्मा", "हिन्दी साहित्य", "ve-din"),
    ("लाल टीन की छत", "निर्मल वर्मा", "हिन्दी साहित्य", "lal-teen-ki-chhat"),
    ("अंतिम अरण्य", "निर्मल वर्मा", "हिन्दी साहित्य", "antim-aranya"),
    ("धुंध की आवाज़", "निर्मल वर्मा", "हिन्दी साहित्य", "dhundh-ki-awaz"),
    ("रात का रिपोर्टर", "निर्मल वर्मा", "हिन्दी साहित्य", "raat-ka-reporter"),
    ("चित्रलेखा", "भगवती चरण वर्मा", "हिन्दी साहित्य", "chitralekha"),
    ("टेढ़े-मेढ़े रास्ते", "भगवती चरण वर्मा", "हिन्दी साहित्य", "tedhe-medhe-raste"),
    ("चक्रव्यूह", "भगवती चरण वर्मा", "हिन्दी साहित्य", "chakravyuh"),
    ("भूले बिसरे चित्र", "भगवती चरण वर्मा", "हिन्दी साहित्य", "bhule-bisre-chitra"),
    ("पिंजर", "अमृता प्रीतम", "हिन्दी साहित्य", "pinjar"),
    ("रसीदी टिकट", "अमृता प्रीतम", "हिन्दी साहित्य", "rasidi-ticket"),
    ("आधा गाँव", "राही मासूम रज़ा", "हिन्दी साहित्य", "aadhagaon"),
    ("टोपी शुक्ला", "राही मासूम रज़ा", "हिन्दी साहित्य", "topi-shukla"),
    ("ओस की बूँद", "राही मासूम रज़ा", "हिन्दी साहित्य", "os-ki-boond"),
    ("नौकर की कमीज़", "विनोद कुमार शुक्ल", "हिन्दी साहित्य", "naukar-ki-kameez"),
    ("खिलेगा तो देखेंगे", "विनोद कुमार शुक्ल", "हिन्दी साहित्य", "khilega-to-dekhenge"),
    ("दीवार में एक खिड़की रहती थी", "विनोद कुमार शुक्ल", "हिन्दी साहित्य", "deewar-mein-ek-khidki"),
    ("काशी का अस्सी", "काशीनाथ सिंह", "हिन्दी साहित्य", "kashi-ka-assi"),
    ("रेहन पर रग्घू", "काशीनाथ सिंह", "हिन्दी साहित्य", "rehan-par-ragghu"),
    ("अपना मोर्चा", "काशीनाथ सिंह", "हिन्दी साहित्य", "apna-morcha"),
    ("रामचरितमानस", "गोस्वामी तुलसीदास", "दर्शन व अध्यात्म", "ramcharitmanas"),
    ("विनय पत्रिका", "गोस्वामी तुलसीदास", "दर्शन व अध्यात्म", "vinay-patrika"),
    ("कबीर बीजक", "कबीर", "दर्शन व अध्यात्म", "kabir-beejak"),
    ("साखी", "कबीर", "दर्शन व अध्यात्म", "kabir-sakhi"),
    ("सूरसागर", "सूरदास", "हिन्दी साहित्य", "soorsagar"),
    ("पद्मावत", "मलिक मुहम्मद जायसी", "हिन्दी साहित्य", "padmavat"),
    ("बिहारी सतसई", "बिहारीलाल", "हिन्दी साहित्य", "bihari-satsai"),
    ("मीरा पदावली", "मीराबाई", "हिन्दी साहित्य", "meera-padavali"),
    ("गीतांजलि", "रवींद्रनाथ ठाकुर", "हिन्दी साहित्य", "geetanjali-hi"),
    ("गोरा", "रवींद्रनाथ ठाकुर", "हिन्दी साहित्य", "gora-hi"),
    ("डाकघर", "रवींद्रनाथ ठाकुर", "हिन्दी साहित्य", "dakghar"),
    ("पोस्टमास्टर", "रवींद्रनाथ ठाकुर", "हिन्दी साहित्य", "postmaster"),
    ("घरे-बाइरे", "रवींद्रनाथ ठाकुर", "हिन्दी साहित्य", "ghare-baire-hi"),
    ("चोखेर बाली", "रवींद्रनाथ ठाकुर", "हिन्दी साहित्य", "chokher-bali-hi"),
    ("अंधेर नगरी", "भारतेंदु हरिश्चंद्र", "हिन्दी साहित्य", "andher-nagari"),
    ("भारत दुर्दशा", "भारतेंदु हरिश्चंद्र", "हिन्दी साहित्य", "bharat-durdasha"),
    ("सत्य हरिश्चंद्र", "भारतेंदु हरिश्चंद्र", "हिन्दी साहित्य", "satya-harishchandra"),
    ("चंद्रकांता", "देवकीनंदन खत्री", "रहस्य व थ्रिलर", "chandrakanta"),
    ("चंद्रकांता संतति", "देवकीनंदन खत्री", "रहस्य व थ्रिलर", "chandrakanta-santati"),
    ("भूतनाथ", "देवकीनंदन खत्री", "रहस्य व थ्रिलर", "bhootnath"),
    ("झाँसी की रानी", "वृंदावनलाल वर्मा", "हिन्दी साहित्य", "jhansi-ki-rani"),
    ("मृगनयनी", "वृंदावनलाल वर्मा", "हिन्दी साहित्य", "mrignayani"),
    ("गढ़ कुंडार", "वृंदावनलाल वर्मा", "हिन्दी साहित्य", "garh-kundar"),
    ("अहिल्याबाई", "वृंदावनलाल वर्मा", "हिन्दी साहित्य", "ahilyabai"),
    ("माधवजी सिंधिया", "वृंदावनलाल वर्मा", "हिन्दी साहित्य", "madhavji-scindia"),
    ("मृत्युंजय", "शिवाजी सावंत", "हिन्दी साहित्य", "mrityunjay"),
    ("ययाति", "वि. स. खांडेकर", "हिन्दी साहित्य", "yayati"),
    ("हयवदन", "गिरीश कर्नाड", "हिन्दी साहित्य", "hayavadana-hi"),
    ("टुन्नू की वापसी", "शानी", "हिन्दी साहित्य", "tunnu-ki-wapsi"),
    ("काला जल", "शानी", "हिन्दी साहित्य", "kala-jal"),
    ("कलिकथा वाया बाईपास", "अलका सरावगी", "हिन्दी साहित्य", "kalikatha-via-bypass"),
    ("शेष कादंबरी", "अलका सरावगी", "हिन्दी साहित्य", "shesh-kadambari"),
    ("एक और अंत", "कमलेश्वर", "हिन्दी साहित्य", "ek-aur-ant"),
    ("कितने पाकिस्तान", "कमलेश्वर", "हिन्दी साहित्य", "kitne-pakistan"),
    ("अधूरी आवाज़", "कमलेश्वर", "हिन्दी साहित्य", "adhuri-awaz"),
    ("तीसरा सप्तक", "अज्ञेय संपादित", "हिन्दी साहित्य", "teesra-saptak"),
    ("तार सप्तक", "अज्ञेय संपादित", "हिन्दी साहित्य", "taar-saptak"),
    ("चाँद का मुँह टेढ़ा है", "गजानन माधव मुक्तिबोध", "हिन्दी साहित्य", "chand-ka-munh-tedha-hai"),
    ("अंधेरे में", "गजानन माधव मुक्तिबोध", "हिन्दी साहित्य", "andhere-mein-muktibodh"),
    ("भारत का भाग्य विधाता", "जयशंकर प्रसाद", "हिन्दी साहित्य", "bharat-bhagya"),
    ("हिंदी साहित्य का इतिहास", "आचार्य रामचंद्र शुक्ल", "इतिहास", "hindi-sahitya-ka-itihas"),
    ("चिंतामणि", "आचार्य रामचंद्र शुक्ल", "दर्शन व अध्यात्म", "chintamani"),
    ("कबीर", "हजारी प्रसाद द्विवेदी", "हिन्दी साहित्य", "kabir-dwivedi"),
    ("बाणभट्ट की आत्मकथा", "हजारी प्रसाद द्विवेदी", "हिन्दी साहित्य", "banbhatt-ki-atmakatha"),
    ("अनामदास का पोथा", "हजारी प्रसाद द्विवेदी", "हिन्दी साहित्य", "anamdas-ka-potha"),
    ("आलमगिर का भारत", "राहुल सांकृत्यायन", "इतिहास", "rahul-sankrityayan"),
    ("वोल्गा से गंगा", "राहुल सांकृत्यायन", "इतिहास", "volga-se-ganga"),
    ("मेरी जीवन यात्रा", "राहुल सांकृत्यायन", "जीवनी", "meri-jeevan-yatra"),
    ("सत्यार्थ प्रकाश", "स्वामी दयानंद सरस्वती", "दर्शन व अध्यात्म", "satyarth-prakash"),
    ("राजयोग", "स्वामी विवेकानंद", "दर्शन व अध्यात्म", "rajyog"),
    ("कर्मयोग", "स्वामी विवेकानंद", "दर्शन व अध्यात्म", "karmayog"),
    ("ज्ञानयोग", "स्वामी विवेकानंद", "दर्शन व अध्यात्म", "gyanyog"),
    ("भक्तियोग", "स्वामी विवेकानंद", "दर्शन व अध्यात्म", "bhaktimarg"),
    ("पतंजलि योगसूत्र", "महर्षि पतंजलि", "दर्शन व अध्यात्म", "patanjali-yogasutra"),
    ("भगवद गीता", "व्यास", "दर्शन व अध्यात्म", "bhagavad-gita-hi"),
    ("उपनिषद सार", "विविध ऋषि", "दर्शन व अध्यात्म", "upanishad-saar"),
    ("विवेकचूड़ामणि", "आदि शंकराचार्य", "दर्शन व अध्यात्म", "vivekachudamani"),
    ("अष्टावक्र गीता", "अष्टावक्र", "दर्शन व अध्यात्म", "ashtavakra-gita"),
    ("रामचरितमानस सुंदरकांड", "तुलसीदास", "दर्शन व अध्यात्म", "sundarkand"),
    ("हनुमान चालीसा", "तुलसीदास", "दर्शन व अध्यात्म", "hanuman-chalisa"),
    ("शिव महापुराण", "व्यास परंपरा", "दर्शन व अध्यात्म", "shiv-mahapuran"),
    ("मार्कण्डेय पुराण", "व्यास परंपरा", "दर्शन व अध्यात्म", "markandeya-puran"),
    ("नारद पुराण", "व्यास परंपरा", "दर्शन व अध्यात्म", "narad-puran"),
    ("विष्णु पुराण", "व्यास परंपरा", "दर्शन व अध्यात्म", "vishnu-puran"),
    ("देवी भागवत पुराण", "व्यास परंपरा", "दर्शन व अध्यात्म", "devi-bhagavat"),
    ("कूर्म पुराण", "व्यास परंपरा", "दर्शन व अध्यात्म", "kurma-puran"),
    ("ध्यान सूत्र", "महर्षि पतंजलि परंपरा", "दर्शन व अध्यात्म", "dhyan-sutra"),
    ("भक्ति सूत्र", "नारद", "दर्शन व अध्यात्म", "bhakti-sutra"),
    ("आचारांग सूत्र", "जैन आगम", "दर्शन व अध्यात्म", "acharanga-sutra"),
    ("जिन सूत्र", "जैन आगम", "दर्शन व अध्यात्म", "jina-sutra"),
    ("जपुजी साहिब", "गुरु नानक", "दर्शन व अध्यात्म", "japji-sahib"),
    ("विनय पत्रिका सार", "तुलसीदास", "दर्शन व अध्यात्म", "vinay-patrika-saar"),
    ("नागार्जुन कविताएँ", "नागार्जुन", "हिन्दी साहित्य", "nagarjun-kavita"),
    ("पत्रहीन नग्न गाछ", "नागार्जुन", "हिन्दी साहित्य", "patraheen-nagna-gachh"),
    ("युगधारा", "नागार्जुन", "हिन्दी साहित्य", "yugdhara"),
    ("बलचनमा", "नागार्जुन", "हिन्दी साहित्य", "balchanma"),
    ("वरुण के बेटे", "नागार्जुन", "हिन्दी साहित्य", "varun-ke-bete"),
    ("एक कंठ विषपायी", "दुष्यंत कुमार", "हिन्दी साहित्य", "ek-kanth-vishpayi"),
    ("साये में धूप", "दुष्यंत कुमार", "हिन्दी साहित्य", "saye-mein-dhoop"),
    ("आत्मजयी", "कुँवर नारायण", "हिन्दी साहित्य", "atmajayi"),
    ("कोई दूसरा नहीं", "कुँवर नारायण", "हिन्दी साहित्य", "koi-doosra-nahin"),
    ("कविता के नए प्रतिमान", "नामवर सिंह", "हिन्दी साहित्य", "kavita-ke-naye-pratiman"),
    ("छायावाद", "नामवर सिंह", "हिन्दी साहित्य", "chhayavad"),
    ("पृथ्वीराज रासो", "चंदबरदाई", "हिन्दी साहित्य", "prithviraj-raso"),
    ("आल्हा", "जगनिक", "हिन्दी साहित्य", "alha"),
    ("बीसलदेव रासो", "नरपति नाल्ह", "हिन्दी साहित्य", "bisaldev-raso"),
    ("पद्मावती", "मलिक मुहम्मद जायसी", "हिन्दी साहित्य", "padmavati"),
    ("झाँसी की रानी लक्ष्मीबाई", "वृंदावनलाल वर्मा", "इतिहास", "rani-lakshmibai"),
    ("परीक्षा गुरु", "लाला श्रीनिवास दास", "हिन्दी साहित्य", "pariksha-guru"),
    ("भाग्यवती", "श्रद्धाराम फिल्लौरी", "हिन्दी साहित्य", "bhagyawati"),
    ("चंद्रकांता का रहस्य", "देवकीनंदन खत्री", "रहस्य व थ्रिलर", "chandrakanta-rahasya"),
    ("सुनीता", "जैनेंद्र कुमार", "हिन्दी साहित्य", "sunita-jainendra"),
    ("त्यागपत्र", "जैनेंद्र कुमार", "हिन्दी साहित्य", "tyagpatra"),
    ("कल्याणी", "जैनेंद्र कुमार", "हिन्दी साहित्य", "kalyani"),
    ("सुखदा", "जैनेंद्र कुमार", "हिन्दी साहित्य", "sukhda"),
    ("अनाम स्वामी", "जैनेंद्र कुमार", "हिन्दी साहित्य", "anam-swami"),
    ("शेखर से सात वर्ष बाद", "अज्ञेय", "हिन्दी साहित्य", "shekhar-saat-varsh"),
    ("नदी के द्वीप के पार", "अज्ञेय", "हिन्दी साहित्य", "nadi-ke-dweep-paar"),
    ("बिल्ली और बंदर", "प्रेमचंद", "हिन्दी साहित्य", "billi-aur-bandar"),
    ("दो बैलों की कथा", "प्रेमचंद", "हिन्दी साहित्य", "do-bailon-ki-katha"),
    ("बड़े भाई साहब", "प्रेमचंद", "हिन्दी साहित्य", "bade-bhai-sahab"),
    ("गुल्ली डंडा", "प्रेमचंद", "हिन्दी साहित्य", "gulli-danda"),
    ("नमक का दारोगा", "प्रेमचंद", "हिन्दी साहित्य", "namak-ka-daroga"),
    ("पंच परमेश्वर", "प्रेमचंद", "हिन्दी साहित्य", "panch-parmeshwar"),
    ("मंत्र", "प्रेमचंद", "हिन्दी साहित्य", "mantra-premchand"),
    ("मुक्तिधन", "प्रेमचंद", "हिन्दी साहित्य", "muktidhan"),
    ("आत्मनिर्भर भारत निबंध", "रामधारी सिंह दिनकर", "इतिहास", "atmanirbhar-dinkar"),
    ("संस्कृति, राष्ट्र और समाज", "रामधारी सिंह दिनकर", "इतिहास", "sanskriti-rashtra"),
    ("कुरुक्षेत्र युद्ध-काव्य", "रामधारी सिंह दिनकर", "हिन्दी साहित्य", "kurukshetra-kavya"),
    ("उर्वशी काव्य-नाटक", "रामधारी सिंह दिनकर", "हिन्दी साहित्य", "urvashi-natak"),
    ("प्रियाप्रवास", "अयोध्या सिंह उपाध्याय हरिऔध", "हिन्दी साहित्य", "priyapravas"),
    ("वैदेही वनवास", "अयोध्या सिंह उपाध्याय हरिऔध", "हिन्दी साहित्य", "vaidehi-vanvas"),
    ("साकेत महाकाव्य", "मैथिलीशरण गुप्त", "हिन्दी साहित्य", "saket-mahakavya"),
    ("द्वापर", "मैथिलीशरण गुप्त", "हिन्दी साहित्य", "dwapar"),
    ("सिद्धराज", "मैथिलीशरण गुप्त", "हिन्दी साहित्य", "siddharaj"),
    ("अनामिका काव्य", "निराला", "हिन्दी साहित्य", "anamika-kavya"),
    ("बेला", "निराला", "हिन्दी साहित्य", "bela-nirala"),
    ("कुकुरमुत्ता", "निराला", "हिन्दी साहित्य", "kukurmutta"),
    ("राम की शक्तिपूजा व्याख्या", "निराला", "हिन्दी साहित्य", "shaktipooja-vyakhya"),
    ("चिदंबरा", "सुमित्रानंदन पंत", "हिन्दी साहित्य", "chidambara"),
    ("लोकायतन", "सुमित्रानंदन पंत", "हिन्दी साहित्य", "lokayatan"),
    ("अतिमा", "महादेवी वर्मा", "हिन्दी साहित्य", "atima"),
    ("दीपशिखा", "महादेवी वर्मा", "हिन्दी साहित्य", "deepshikha"),
    ("क्षणदा", "महादेवी वर्मा", "हिन्दी साहित्य", "kshanda"),
    ("अग्निपथ", "हरिवंश राय बच्चन", "हिन्दी साहित्य", "agnipath"),
    ("मिलन यामिनी", "हरिवंश राय बच्चन", "हिन्दी साहित्य", "milan-yamini"),
    ("प्रणय पत्रिका", "हरिवंश राय बच्चन", "हिन्दी साहित्य", "pranay-patrika"),
    ("धार के इधर-उधर", "अज्ञेय", "हिन्दी साहित्य", "dhar-ke-idhar-udhar"),
    ("इत्यलम्", "अज्ञेय", "हिन्दी साहित्य", "ityalam"),
    ("कितनी नावों में कितनी बार", "अज्ञेय", "हिन्दी साहित्य", "kitni-naavon"),
    ("आँगन के पार", "अज्ञेय", "हिन्दी साहित्य", "angan-ke-paar"),
    ("सात गीत वर्ष", "धर्मवीर भारती", "हिन्दी साहित्य", "saat-geet-varsh"),
    ("कनुप्रिया", "धर्मवीर भारती", "हिन्दी साहित्य", "kanupriya"),
    ("नया समाज", "यशपाल", "हिन्दी साहित्य", "naya-samaj"),
    ("देशद्रोही", "यशपाल", "हिन्दी साहित्य", "deshdrohi"),
    ("पार्टी कामरेड", "यशपाल", "हिन्दी साहित्य", "party-comrade"),
    ("मेरी तेरी उसकी बात", "यशपाल", "हिन्दी साहित्य", "meri-teri-uski-baat"),
    ("क्या भूलूँ क्या याद करूँ", "हरिवंश राय बच्चन", "जीवनी", "kya-bhooloon"),
    ("नीड़ का निर्माण फिर", "हरिवंश राय बच्चन", "जीवनी", "need-ka-nirman"),
    ("बसेरे से दूर", "हरिवंश राय बच्चन", "जीवनी", "basere-se-door"),
    ("दशद्वार से सोपान तक", "हरिवंश राय बच्चन", "जीवनी", "dashdwar-se-sopan"),
]

# Roman sitemap slug → Devanagari title (famous Hindi books on booknomics.com).
ROMAN_HI = {
    "godan": ("गोदान", "मुंशी प्रेमचंद"),
    "gaban": ("गबन", "मुंशी प्रेमचंद"),
    "nirmala": ("निर्मला", "मुंशी प्रेमचंद"),
    "sevasadan": ("सेवासदन", "मुंशी प्रेमचंद"),
    "rangbhoomi": ("रंगभूमि", "मुंशी प्रेमचंद"),
    "madhushala": ("मधुशाला", "हरिवंश राय बच्चन"),
    "kamayani": ("कामायनी", "जयशंकर प्रसाद"),
    "rashmirathi": ("रश्मिरथी", "रामधारी सिंह दिनकर"),
    "kurukshetra": ("कुरुक्षेत्र", "रामधारी सिंह दिनकर"),
    "urvashi": ("उर्वशी", "रामधारी सिंह दिनकर"),
    "shekhar-ek-jivani": ("शेखर: एक जीवनी", "अज्ञेय"),
    "nadi-ke-dweep": ("नदी के द्वीप", "अज्ञेय"),
    "chitralekha": ("चित्रलेखा", "भगवती चरण वर्मा"),
    "saket": ("साकेत", "मैथिलीशरण गुप्त"),
    "yama": ("यामा", "महादेवी वर्मा"),
    "maila-aanchal": ("मैला आंचल", "फणीश्वरनाथ रेणु"),
    "raag-darbari": ("राग दरबारी", "श्रीलाल शुक्ल"),
    "tamas": ("तमस", "भीष्म साहनी"),
    "gunahon-ka-devta": ("गुनाहों का देवता", "धर्मवीर भारती"),
    "suraj-ka-saatvan-ghora": ("सूरज का सातवाँ घोड़ा", "धर्मवीर भारती"),
    "andhayug": ("अंधायुग", "धर्मवीर भारती"),
    "jail-diary-prasad": ("जेल डायरी", "जयशंकर प्रसाद"),
    "dhup-ka-ek-tukda-mannu-bhandari": ("धूप का एक टुकड़ा", "मन्नू भंडारी"),
    "kitne-chaurahe-phanishwarnath-renu": ("कितने चौराहे", "फणीश्वरनाथ रेणु"),
    "ek-akela-raste-mein-nirmal-verma": ("एक अकेला रास्ते में", "निर्मल वर्मा"),
    "dharti-ki-baat-phanishwar-nath-renu": ("धरती की बात", "फणीश्वरनाथ रेणु"),
    "patthar-aur-pankhi-sumitranandan-pant": ("पत्थर और पंखी", "सुमित्रानंदन पंत"),
    "ek-baat-aur-mannu-bhandari": ("एक बात और", "मन्नू भंडारी"),
    "prem-ki-bhiksha-jayshankar-prasad": ("प्रेम की भिक्षा", "जयशंकर प्रसाद"),
    "ek-aur-ek-gyarah-srilal-shukla": ("एक और एक ग्यारह", "श्रीलाल शुक्ल"),
    "patthar-ki-deewar-bhagwati-charan-verma": ("पत्थर की दीवार", "भगवती चरण वर्मा"),
    "ek-aur-kavita-dinkar": ("एक और कविता", "रामधारी सिंह दिनकर"),
    "champaklal-ki-kahaniyan-krishan-chander": ("चंपाकलाल की कहानियाँ", "कृष्ण चंदर"),
    "patthar-ki-zuban-rajendra-yadav": ("पत्थर की ज़ुबान", "राजेंद्र यादव"),
    "surya-ki-ghodi-ramdarash-mishra": ("सूर्य की घोड़ी", "रामदरश मिश्र"),
    "mahan-natak-vrindavan-lal-varma": ("महान नाटक", "वृंदावनलाल वर्मा"),
    "baazigar-shivani": ("बाज़ीगर", "शिवानी"),
    "ek-nadi-vichitra-nadi-namwar-singh": ("एक नदी विचित्र नदी", "नामवर सिंह"),
    "do-beegha-zameen-shailendra": ("दो बीघा ज़मीन", "शैलेंद्र"),
    "charitraheen-sharatchandra": ("चारित्रहीन", "शरतचंद्र चट्टोपाध्याय"),
    "vaishali-ki-nagarvadhu-chatursen": ("वैशाली की नगरवधू", "आचार्य चतुरसेन"),
    "patthar-ka-ghoda-omprakash-valmiki": ("पत्थर का घोड़ा", "ओमप्रकाश वाल्मीकि"),
    "amrapali-narendra-sharma": ("आम्रपाली", "नरेंद्र शर्मा"),
    "patthar-ki-murten-ramdarash-mishra": ("पत्थर की मूर्तियाँ", "रामदरश मिश्र"),
    "ek-vriksha-ki-chhaon-ram-nath-awasthi": ("एक वृक्ष की छाँव", "रामनाथ अवस्थी"),
    "katha-sagar-premchand": ("कथा सागर", "मुंशी प्रेमचंद"),
    "raat-ki-awaaz-krishna-sobti": ("रात की आवाज़", "कृष्णा सोबती"),
    "ek-samvad-mahadevi-varma": ("एक संवाद", "महादेवी वर्मा"),
    "aakhiri-kalam-suryakant-tripathi-nirala": ("आखिरी कलम", "सूर्यकांत त्रिपाठी निराला"),
    "sone-ki-chidiya-rahul-sankrityayan": ("सोने की चिड़िया", "राहुल सांकृत्यायन"),
    "sankalp-yashwant-dinkar-pendharkar": ("संकल्प", "यशवंत दिनकर पेंढारकर"),
    "teen-ekanki-bhagwati-charan-verma": ("तीन एकांकी", "भगवती चरण वर्मा"),
    "dharti-ki-awaaz-nagarjune": ("धरती की आवाज़", "नागार्जुन"),
    "ek-akeli-aurat-bhagwati-charan-verma": ("एक अकेली औरत", "भगवती चरण वर्मा"),
    "chaurahon-par-kamleshwar": ("चौराहों पर", "कमलेश्वर"),
    "do-mulaqatein-rajendra-yadav": ("दो मुलाकातें", "राजेंद्र यादव"),
    "chidiya-ghar-ki-kahaniyan-krishan-chander": ("चिड़ियाघर की कहानियाँ", "कृष्ण चंदर"),
    "ek-savera-jo-abya-aaya-harishankar-parsai": ("एक सवेरा जो अब आया", "हरिशंकर परसाई"),
    "kavita-ke-bahane-kunwar-narayan": ("कविता के बहाने", "कुँवर नारायण"),
    "ek-aur-maleecha-kamleshwar": ("एक और मलेच्छ", "कमलेश्वर"),
    "neeli-ghas-krishna-baldev-vaaid": ("नीली घास", "कृष्ण बलदेव वैद"),
    "kalam-ka-sipahi-amrit-rai": ("कलम का सिपाही", "अमृत राय"),
    "sone-ka-anda-krishan-chander": ("सोने का अंडा", "कृष्ण चंदर"),
    "devdas-sharatchandra": ("देवदास", "शरतचंद्र चट्टोपाध्याय"),
    "ek-bund-sahsa-kedarnath-singh": ("एक बूँद सहसा", "केदारनाथ सिंह"),
    "ek-aur-savera-namwar-singh": ("एक और सवेरा", "नामवर सिंह"),
    "parineeta-sharatchandra": ("परिणीता", "शरतचंद्र चट्टोपाध्याय"),
    "pratigya-premchand": ("प्रतिज्ञा", "मुंशी प्रेमचंद"),
    "kavita-ki-raat-mahadevi-varma": ("कविता की रात", "महादेवी वर्मा"),
    "ek-purani-kahani-bhisham-sahni": ("एक पुरानी कहानी", "भीष्म साहनी"),
    "do-rahe-mahadevi-varma": ("दो राहें", "महादेवी वर्मा"),
    "kahan-kahan-se-guzar-aaya-suryakant-tripathi-nirala": ("कहाँ कहाँ से गुज़र आया", "सूर्यकांत त्रिपाठी निराला"),
    "chitra-rabindranath-tagore": ("चित्रा", "रवींद्रनाथ ठाकुर"),
    "patthar-ki-baat-ramdarash-mishra": ("पत्थर की बात", "रामदरश मिश्र"),
    "ek-pyaar-ki-baat-jainendra-kumar": ("एक प्यार की बात", "जैनेंद्र कुमार"),
    "dharti-dhan-na-apna-jagdish-chandra": ("धरती धन न अपना", "जगदीश चंद्र"),
    "kahan-se-kahan-tak-ajneya": ("कहाँ से कहाँ तक", "अज्ञेय"),
    "sone-ka-pinjra-shivani": ("सोने का पिंजरा", "शिवानी"),
    "dharti-ki-beti-shivani": ("धरती की बेटी", "शिवानी"),
    "barah-mah-kaifi-azmi": ("बारह माह", "कैफ़ी आज़मी"),
    "ek-pyaar-kahani-jainendra-kumar": ("एक प्यार कहानी", "जैनेंद्र कुमार"),
    "antahpur-madhav-sharma": ("अंतःपुर", "माधव शर्मा"),
    "ek-chitthi-sadguru-prasad": ("एक चिट्ठी", "सद्गुरु प्रसाद"),
    "chandni-raat-aur-kavita-sumitranandan-pant": ("चाँदनी रात और कविता", "सुमित्रानंदन पंत"),
    "ek-kahani-jo-sach-hui-madhav-juliyani": ("एक कहानी जो सच हुई", "माधव जुलियानी"),
    "suryast-ki-awaaz-kedarnath-agrawal": ("सूर्यास्त की आवाज़", "केदारनाथ अग्रवाल"),
    "ek-samasya-aur-nirala": ("एक समस्या", "सूर्यकांत त्रिपाठी निराला"),
    "ponniyin-selvan-kalki-krishnamurthy": ("पोननियिन सेल्वन", "कल्कि कृष्णमूर्ति"),
    "sivagamiyin-sabatham-kalki-krishnamurthy": ("शिवागामियिन शपथम्", "कल्कि कृष्णमूर्ति"),
    "thyaga-bhoomi-kalki-krishnamurthy": ("त्यागभूमि", "कल्कि कृष्णमूर्ति"),
    "kalvanin-kadhali-kalki-krishnamurthy": ("कल्वनिन् कादली", "कल्कि कृष्णमूर्ति"),
    "chithira-pavai-akilan": ("चित्रपावै", "अकिलन"),
    "paavai-vilakku-akilan": ("पावै विलक्कु", "अकिलन"),
    "vengayin-maindhan-akilan": ("वेंगयिन मैन्दन", "अकिलन"),
    "vetrithirunagar-akilan": ("वेट्रितिरुनगर", "अकिलन"),
    "thunaivi-akilan": ("तुणैवि", "अकिलन"),
    "oru-nadigai-nadagam-parkiral-d-jayakanthan": ("ओरु नडिगै नाडगम पारकिराल", "जयकांतन"),
    "unnaipol-oruvan-d-jayakanthan": ("उन्नैपोल ओरुवन", "जयकांतन"),
    "yaarukkaga-azhudhaan-d-jayakanthan": ("यारुक्काग अषुदान", "जयकांतन"),
    "mogamul-t-janakiraman": ("मोगमूल", "टी. जानकीरमन"),
    "amma-vandhaal-t-janakiraman": ("अम्मा वंदाल", "टी. जानकीरमन"),
    "kanavu-thozhirchalai-sujatha": ("कनवु तोषिरशालै", "सुजाता"),
    "computer-gramam-sujatha": ("कंप्यूटर ग्रामम", "सुजाता"),
    "oruththi-ninaikayile-sujatha": ("ओरुत्ति निनैकयिले", "सुजाता"),
    "aadhalinal-kadhal-seiveer-sujatha": ("आदलिनाल कादल सेइवीर", "सुजाता"),
    "endravathu-oru-nal-sujatha": ("एन्द्रवदु ओरु नाल", "सुजाता"),
    "vishnupuram-jeyamohan": ("विष्णुपुरम", "जयमोहन"),
    "aram-jeyamohan": ("अरम", "जयमोहन"),
    "madhorubhagan-perumal-murugan": ("मधोरुभगन", "पेरुमाल मुरुगन"),
    "koolamadari-perumal-murugan": ("कूलमादारी", "पेरुमाल मुरुगन"),
    "kanganam-perumal-murugan": ("कंगनम", "पेरुमाल मुरुगन"),
    "nizhal-mutram-perumal-murugan": ("निषल मुट्रम", "पेरुमाल मुरुगन"),
    "karukku-bama": ("करुक्कु", "बामा"),
    "kaval-kottam-su-venkatesan": ("कवल कोट्टम", "सु. वेंकटेशन"),
    "velpari-su-venkatesan": ("वेलपारि", "सु. वेंकटेशन"),
    "agnaadi-poomani": ("अग्नाडी", "पूमणि"),
    "piragu-poomani": ("पिरगु", "पूमणि"),
    "kadal-pura-sandilyan": ("कडल पुरा", "सांडिल्यन"),
    "raja-muthirai-sandilyan": ("राजा मुदिरै", "सांडिल्यन"),
    "nandu-sivasankari": ("नंदू", "शिवसंकरी"),
    "oru-manithanin-kathai-sivasankari": ("ओरु मनिदनिन् कदै", "शिवसंकरी"),
    "koveru-kazhuthaigal-imayam": ("कोवेरु कषुदैगळ", "इमयम"),
    "selladha-panam-imayam": ("सेल्लद पणम", "इमयम"),
    "pethavan-imayam": ("पेदवन", "इमयम"),
    "gopallapurathu-makkal-ki-rajanarayanan": ("गोपल्लपुरत्तु मक्कळ", "की. राजनारायणन"),
    "thanneer-ashokamitran": ("तण्णीर", "अशोकमित्रन"),
    "kurinji-malar-na-parthasarathy": ("कुरिंजि मलर", "ना. पार्थसारथी"),
    "udayar-balakumaran": ("उदयार", "बालकुमारन"),
    "kuzhanthaigal-pengal-aangal-sundara-ramaswamy": ("कुषंदैगळ पेन्गळ आंगळ", "सुंदर रामस्वामी"),
    "samskara-u-r-ananthamurthy": ("संस्कार", "यू. आर. अनंतमूर्ति"),
    "bharathipura-u-r-ananthamurthy": ("भारतीपुर", "यू. आर. अनंतमूर्ति"),
    "parva-s-l-bhyrappa": ("पर्व", "एस. एल. भैरप्पा"),
    "vamshavruksha-s-l-bhyrappa": ("वंशवृक्ष", "एस. एल. भैरप्पा"),
    "daatu-s-l-bhyrappa": ("दाटु", "एस. एल. भैरप्पा"),
    "mandra-s-l-bhyrappa": ("मंद्र", "एस. एल. भैरप्पा"),
    "naayi-neralu-s-l-bhyrappa": ("नायि नेरलु", "एस. एल. भैरप्पा"),
    "uttara-kaanda-s-l-bhyrappa": ("उत्तर कांड", "एस. एल. भैरप्पा"),
    "marali-mannige-k-shivaram-karanth": ("मरलि मण्णिगे", "के. शिवराम कारंत"),
    "chomana-dudi-k-shivaram-karanth": ("चोमना डुडि", "के. शिवराम कारंत"),
    "mookajjiya-kanasugalu-k-shivaram-karanth": ("मूकज्जिय कनसुगळु", "के. शिवराम कारंत"),
    "bettada-jeeva-k-shivaram-karanth": ("बेट्टद जीव", "के. शिवराम कारंत"),
    "malegalalli-madumagalu-kuvempu": ("मलेगलल्लि मदुमगळु", "कुवेम्पु"),
    "sri-ramayana-darshanam-kuvempu": ("श्री रामायण दर्शनम्", "कुवेम्पु"),
    "nagarahaavu-t-r-subba-rao": ("नगरहावु", "टी. आर. सुब्बाराव"),
    "chandavalliya-thota-t-r-subba-rao": ("चंदवल्लिय तोटा", "टी. आर. सुब्बाराव"),
    "bidugadeya-bedi-t-r-subba-rao": ("बिडुगदेय बेडि", "टी. आर. सुब्बाराव"),
    "chakrateertha-t-r-subba-rao": ("चक्रतीर्थ", "टी. आर. सुब्बाराव"),
    "jugari-cross-poornachandra-tejaswi": ("जुगारि क्रॉस", "पूरणचंद्र तेजस्वी"),
    "chidambara-rahasya-poornachandra-tejaswi": ("चिदंबर रहस्य", "पूरणचंद्र तेजस्वी"),
    "abachurina-post-office-poornachandra-tejaswi": ("अबचूरिन पोस्ट ऑफिस", "पूरणचंद्र तेजस्वी"),
    "kaadu-srikrishna-alanahalli": ("काडु", "श्रीकृष्ण अलनहल्लि"),
    "bhujangayyana-dashavatara-srikrishna-alanahalli": ("भुजंगय्यन दशावतार", "श्रीकृष्ण अलनहल्लि"),
    "gejje-pooje-m-k-indira": ("गेज्जे पूजे", "एम. के. इंदिरा"),
    "phaniyamma-m-k-indira": ("फणियम्मा", "एम. के. इंदिरा"),
    "hoobana-m-k-indira": ("हूबना", "एम. के. इंदिरा"),
    "nagamandala-girish-karnad": ("नागमंडल", "गिरीश कर्नाड"),
    "tughlaq-girish-karnad": ("तुगलक", "गिरीश कर्नाड"),
    "jokumaraswami-chandrashekhara-kambara": ("जोकुमारस्वामी", "चंद्रशेखर कंबार"),
    "sirisampige-chandrashekhara-kambara": ("सिरिसंपिगे", "चंद्रशेखर कंबार"),
    "singarevva-mattu-aramane-chandrashekhara-kambara": ("सिंगरेव्व मत्तु अरमने", "चंद्रशेखर कंबार"),
    "kusumabale-devanur-mahadeva": ("कुसुमाबले", "देवनूर महादेव"),
    "gandhi-banda-h-nagaveni": ("गांधी बंड", "एच. नागवेणी"),
    "veyi-padagalu-viswanatha-satyanarayana": ("वेयि पडगळु", "विश्वनाथ सत्यनारायण"),
    "ramayana-kalpavrukshamu-viswanatha-satyanarayana": ("रामायण कल्पवृक्षमु", "विश्वनाथ सत्यनारायण"),
    "ekaveera-viswanatha-satyanarayana": ("एकवीरा", "विश्वनाथ सत्यनारायण"),
    "kanyasulkam-gurajada-apparao": ("कन्यासुलकम्", "गुरजाडा अप्पाराव"),
    "alpajeevi-rachakonda-viswanatha-sastry": ("अल्पजीवी", "रचकोंडा विश्वनाथ शास्त्री"),
    "raju-mahishi-rachakonda-viswanatha-sastry": ("राजु महिषि", "रचकोंडा विश्वनाथ शास्त्री"),
    "chivaraku-migiledi-buchi-babu": ("चिवरकु मिगिलेदि", "बूचि बाबू"),
    "vimuktha-volga": ("विमुक्ता", "वोल्गा"),
    "swechcha-volga": ("स्वेच्छा", "वोल्गा"),
    "gulabilu-volga": ("गुलाबिलु", "वोल्गा"),
    "gabbilam-gurram-jashuva": ("गब्बिलम्", "गुर्रम जाशुआ"),
    "maidanam-chalam": ("मैदानम्", "चालम"),
    "himabindu-adavi-bapiraju": ("हिमाबिंदु", "आदवि बापिराजु"),
    "gona-ganna-reddy-adavi-bapiraju": ("गोना गन्न रेड्डी", "आदवि बापिराजु"),
    "tufanu-adavi-bapiraju": ("तुफानु", "आदवि बापिराजु"),
    "viswambhara-c-narayana-reddy": ("विश्वंभरा", "सी. नारायण रेड्डी"),
    "karpura-vasantharayalu-c-narayana-reddy": ("कर्पूर वसंतरायलु", "सी. नारायण रेड्डी"),
    "malapalli-unnava-lakshminarayana": ("मलपल्लि", "उन्नव लक्ष्मीनारायण"),
    "janaki-vimukti-muppala-ranganayakamma": ("जानकी विमुक्ति", "मुप्पाला रंगनायकम्मा"),
    "balipitham-muppala-ranganayakamma": ("बलिपीठम्", "मुप्पाला रंगनायकम्मा"),
    "ampasayya-ampasayya-naveen": ("अम्पासय्या", "अम्पासय्या नवीन"),
    "antasravanti-ampasayya-naveen": ("अंतस्रवंति", "अम्पासय्या नवीन"),
    "mullapodalu-ampasayya-naveen": ("मुल्लपोडलु", "अम्पासय्या नवीन"),
    "antarani-vasantam-g-kalyana-rao": ("अंतरानि वसंतम्", "जी. कल्याण राव"),
    "chillara-devullu-dasarathi-rangacharya": ("चिल्लर देवुल्लु", "दासरथी रंगाचार्य"),
    "agni-poolu-yaddanapudi-sulochana-rani": ("अग्निपूलु", "यड्डनपुडि सुलोचना रानी"),
    "bangaaru-kalalu-yaddanapudi-sulochana-rani": ("बंगारु काललु", "यड्डनपुडि सुलोचना रानी"),
    "pandita-parameswara-sastry-veelunama-tripuraneni-gopichand": ("पंडित परमेश्वर शास्त्री वीलुनामा", "त्रिपुरानेनि गोपीचंद"),
    "asamardhuni-jeevayatra-tripuraneni-gopichand": ("असमर्थुनि जीवयात्रा", "त्रिपुरानेनि गोपीचंद"),
    "chemmeen-thakazhi-sivasankara-pillai": ("चम्मीन", "तकषि शिवशंकर पिल्लै"),
    "randidangazhi-thakazhi-sivasankara-pillai": ("रंडिडंगाषि", "तकषि शिवशंकर पिल्लै"),
    "thottiyude-makan-thakazhi-sivasankara-pillai": ("तोट्टियुडे मकन", "तकषि शिवशंकर पिल्लै"),
    "enippadikal-thakazhi-sivasankara-pillai": ("एनिप्पडिकळ", "तकषि शिवशंकर पिल्लै"),
    "aadujeevitham-benyamin": ("आडुजीवितम्", "बिन्यामीन"),
    "manjaveyil-maranangal-benyamin": ("मंजवेयिल मरणंगळ", "बिन्यामीन"),
    "naalukettu-m-t-vasudevan-nair": ("नालुकेट्टु", "एम. टी. वासुदेवन नायर"),
    "kaalam-m-t-vasudevan-nair": ("कालम्", "एम. टी. वासुदेवन नायर"),
    "iruttinte-athmavu-m-t-vasudevan-nair": ("इरुत्तिन्टे आत्मवु", "एम. टी. वासुदेवन नायर"),
    "olavum-theeravum-m-t-vasudevan-nair": ("ओलवुम् तीरवुम्", "एम. टी. वासुदेवन नायर"),
    "manju-m-t-vasudevan-nair": ("मंजु", "एम. टी. वासुदेवन नायर"),
    "pathummayude-aadu-vaikom-muhammad-basheer": ("पतुम्मायुडे आडु", "वैकम मुहम्मद बशीर"),
    "janmadinam-vaikom-muhammad-basheer": ("जन्मदिनम्", "वैकम मुहम्मद बशीर"),
    "mucheettukalikkarante-makal-vaikom-muhammad-basheer": ("मुचीट्टुकलिक्कारन्टे मकळ", "वैकम मुहम्मद बशीर"),
    "othappu-sarah-joseph": ("ओतप्पु", "सारा जोसेफ"),
    "agnisakshi-lalithambika-antharjanam": ("अग्निसाक्षी", "ललिताम्बिका अंतरजनम्"),
    "khasakkinte-itihasam-o-v-vijayan": ("खसक्किन्टे इतिहासम्", "ओ. वी. विजयन"),
    "madhuram-gayathi-o-v-vijayan": ("मधुरम् गायति", "ओ. वी. विजयन"),
    "dharmapuranam-o-v-vijayan": ("धर्मपुराणम्", "ओ. वी. विजयन"),
    "aarachar-k-r-meera": ("आराचर", "के. आर. मीरा"),
    "meerasadhu-k-r-meera": ("मीरासाधु", "के. आर. मीरा"),
    "yudasinte-suvishesham-k-r-meera": ("युदासिन्टे सुविषेषम्", "के. आर. मीरा"),
    "oru-desathinte-katha-s-k-pottekkatt": ("ओरु देशत्तिन्टे कथा", "एस. के. पोट्टेक्काट"),
    "oru-theruvinte-katha-s-k-pottekkatt": ("ओरु तेरुविन्टे कथा", "एस. के. पोट्टेक्काट"),
    "naadan-premam-s-k-pottekkatt": ("नाडन प्रेमम्", "एस. के. पोट्टेक्काट"),
    "marthandavarma-c-v-raman-pillai": ("मार्तांडवर्मा", "सी. वी. रामन पिल्लै"),
    "ramaraja-bahadur-c-v-raman-pillai": ("रामराज बहादुर", "सी. वी. रामन पिल्लै"),
    "yakshi-malayattoor-ramakrishnan": ("यक्षी", "मलयाट्टूर रामकृष्णन"),
    "verukal-malayattoor-ramakrishnan": ("वेरुकळ", "मलयाट्टूर रामकृष्णन"),
    "ummachu-uroob": ("उम्मचू", "ऊरूब्"),
    "sundarikalum-sundaranmarum-uroob": ("सुंदरिकळुम् सुंदरन्मार्", "ऊरूब्"),
    "kocharethi-narayan": ("कोचरेति", "नारायण"),
    "ini-njan-urangatte-p-k-balakrishnan": ("इनि जान उरंगट्टे", "पी. के. बालकृष्णन"),
    "pravasam-m-mukundan": ("प्रवासम्", "एम. मुकुंदन"),
    "kesavante-vilapangal-m-mukundan": ("केशवन्टे विलापंगळ", "एम. मुकुंदन"),
    "nellu-p-vatsala": ("नेल्लु", "पी. वत्सला"),
    "agneyam-p-vatsala": ("आग्नेयम्", "पी. वत्सला"),
    "smaraka-silakal-punathil-kunjabdulla": ("स्मारक शिलाकळ", "पुनत्तिल कुंजब्दुल्ला"),
    "marunnu-punathil-kunjabdulla": ("मरुन्नु", "पुनत्तिल कुंजब्दुल्ला"),
    "pattunool-puzhu-s-hareesh": ("पट्टुनूल पुषु", "एस. हरीश"),
    "sugandhi-enna-andal-devanayaki-t-d-ramakrishnan": ("सुगंधि एन्न आंडल देवनायकी", "टी. डी. रामकृष्णन"),
    "ina-pravukal-muttathu-varkey": ("इना प्रवुकळ", "मुट्टात्तु वर्की"),
    "velutha-kathreena-muttathu-varkey": ("वेलुत्त कात्रीना", "मुट्टात्तु वर्की"),
    "padatha-painkili-muttathu-varkey": ("पडात्त पैनकिलि", "मुट्टात्तु वर्की"),
    "shyamchi-aai-sane-guruji": ("श्यामची आई", "साने गुरुजी"),
    "kosala-bhalchandra-nemade": ("कोसला", "भाळचंद्र नेमाडे"),
    "jarila-bhalchandra-nemade": ("जरीला", "भाळचंद्र नेमाडे"),
    "vyakti-ani-valli-p-l-deshpande": ("व्यक्ति आणि वल्ली", "पु. ल. देशपांडे"),
    "batatyachi-chaal-p-l-deshpande": ("बटाट्याची चाळ", "पु. ल. देशपांडे"),
    "apurvai-p-l-deshpande": ("अपूर्वाई", "पु. ल. देशपांडे"),
    "shantata-court-chalu-aahe-vijay-tendulkar": ("शांतता कोर्ट चालू आहे", "विजय तेंडुलकर"),
    "kanyadaan-vijay-tendulkar": ("कन्यादान", "विजय तेंडुलकर"),
    "natsamrat-v-v-shirwadkar": ("नटसम्राट", "वि. वा. शिरवाडकर"),
    "radheya-ranjit-desai": ("राधेय", "रणजीत देसाई"),
    "raja-ravi-varma-ranjit-desai": ("राजा रवि वर्मा", "रणजीत देसाई"),
    "panipat-vishwas-patil": ("पानीपत", "विश्वास पाटील"),
    "baromas-sadanand-deshmukh": ("बारोमास", "सदानंद देशमुख"),
    "banagarwadi-venkatesh-madgulkar": ("बाणगरवाडी", "व्यंकटेश माडगूळकर"),
    "maandeshi-manase-venkatesh-madgulkar": ("मांडेशी मानसे", "व्यंकटेश माडगूळकर"),
    "sattantar-venkatesh-madgulkar": ("सत्तांतर", "व्यंकटेश माडगूळकर"),
    "baluta-daya-pawar": ("बलूत", "दया पवार"),
    "akkarmashi-sharankumar-limbale": ("अक्करमाशी", "शरणकुमार लिंबाळे"),
    "uchalya-laxman-gaikwad": ("उचल्या", "लक्ष्मण गायकवाड"),
    "jina-amucha-baby-kamble": ("जिणं आमुचं", "बेबी कांबळे"),
    "garambicha-bapu-s-n-pendse": ("गारंबीचा बापू", "श्री. ना. पेंडसे"),
    "rathachakra-s-n-pendse": ("रथचक्र", "श्री. ना. पेंडसे"),
    "partner-v-p-kale": ("पार्टनर", "वि. पु. काळे"),
    "mumbai-dinank-arun-sadhu": ("मुंबई दिनांक", "अरुण साधू"),
    "sinhasan-arun-sadhu": ("सिंहासन", "अरुण साधू"),
    "smritichitre-lakshmibai-tilak": ("स्मृतिचित्रे", "लक्ष्मीबाई तिलक"),
    "udya-nanda-khare": ("उद्या", "नंदा खरे"),
    "ringan-krushnat-khot": ("रिंगण", "कृष्णात खोट"),
    "kajalmaya-g-a-kulkarni": ("काजलमाया", "जी. ए. कुलकर्णी"),
    "theru-raghavendra-patil": ("तेरू", "राघवेंद्र पाटील"),
    "zombi-anand-yadav": ("झोंबी", "आनंद यादव"),
    "saraswatichandra-govardhanram-madhavram-tripathi": ("सरस्वतीचंद्र", "गोवर्धनराम माधवराम त्रिपाठी"),
    "angaliyat-joseph-macwan": ("अंगालियात", "जोसेफ मैकवान"),
    "prithvi-vallabh-k-m-munshi": ("पृथ्वीवल्लभ", "कन्हैयालाल माणिकलाल मुंशी"),
    "krishnavatara-k-m-munshi": ("कृष्णावतार", "कन्हैयालाल माणिकलाल मुंशी"),
    "gujarat-no-nath-k-m-munshi": ("गुजरात नो नाथ", "कन्हैयालाल माणिकलाल मुंशी"),
    "bhagwan-kautilya-k-m-munshi": ("भगवान कौटिल्य", "कन्हैयालाल माणिकलाल मुंशी"),
    "karnavati-dhumketu": ("कर्णावती", "धूमकेतु"),
    "paradhin-gujarat-dhumketu": ("पराधीन गुजरात", "धूमकेतु"),
    "rajmukut-dhumketu": ("राजमुकुट", "धूमकेतु"),
    "tulsi-kyaro-zaverchand-meghani": ("तुलसी क्यारो", "झवेरचंद मेघाणी"),
    "sorath-tara-vaheta-pani-zaverchand-meghani": ("सोराठ तारा वहेता पाणी", "झवेरचंद मेघाणी"),
    "manasai-na-diva-zaverchand-meghani": ("मनसई ना दीवा", "झवेरचंद मेघाणी"),
    "saat-pagla-aakashma-kundanika-kapadia": ("सात पगला आकाशमां", "कुंदनिका कापडिया"),
    "tattvamasi-dhruv-bhatt": ("तत्त्वमसि", "ध्रुव भट्ट"),
    "timirpanthi-dhruv-bhatt": ("तिमिरपंथी", "ध्रुव भट्ट"),
    "valamana-pannalal-patel": ("वलमाणा", "पन्नालाल पटेल"),
    "na-chhutke-pannalal-patel": ("ना छूटके", "पन्नालाल पटेल"),
    "socrates-manubhai-pancholi-darshak": ("सुकरात", "मनुभाई पंचोली"),
    "bandighar-manubhai-pancholi-darshak": ("बंदीघर", "मनुभाई पंचोली"),
    "zher-to-pidhan-jani-jani-manubhai-pancholi-darshak": ("झेर तो पिधान जानी जानी", "मनुभाई पंचोली"),
    "akhepatar-bindu-bhatt": ("आखेपातर", "बिंदु भट्ट"),
    "uparvas-kathatrayi-raghuveer-chaudhari": ("उपरवास", "रघुवीर चौधरी"),
    "madhav-kyay-nathi-harindra-dave": ("माधव क्याय नथी", "हरिंद्र दवे"),
    "divya-chakshu-ramanlal-vasantlal-desai": ("दिव्य चक्षु", "रमणलाल वसंतलाल देसाई"),
    "sakkarbar-gunvantrai-acharya": ("सक्करबार", "गुणवंतराय आचार्य"),
    "agantuk-dhiruben-patel": ("आगंतुक", "धीरुबेन पटेल"),
    "anandamath-bankim-chandra-chattopadhyay": ("आनंदमठ", "बंकिम चंद्र चट्टोपाध्याय"),
    "durgeshnandini-bankim-chandra-chattopadhyay": ("दुर्गेशनंदिनी", "बंकिम चंद्र चट्टोपाध्याय"),
    "bishabriksha-bankim-chandra-chattopadhyay": ("विषवृक्ष", "बंकिम चंद्र चट्टोपाध्याय"),
    "devi-chaudhurani-bankim-chandra-chattopadhyay": ("देवी चौधरानी", "बंकिम चंद्र चट्टोपाध्याय"),
    "ganadevata-tarashankar-bandyopadhyay": ("गणदेवता", "ताराशंकर बंद्योपाध्याय"),
    "hansuli-banker-upakatha-tarashankar-bandyopadhyay": ("हांसुली बांकेर उपकथा", "ताराशंकर बंद्योपाध्याय"),
    "hajar-churashir-maa-mahasweta-devi": ("हजार चौरासी की माँ", "महाश्वेता देवी"),
    "chotti-munda-and-his-arrow-mahasweta-devi": ("चोटी मुंडा और उसका तीर", "महाश्वेता देवी"),
    "aranyer-adhikar-mahasweta-devi": ("अरण्येर अधिकार", "महाश्वेता देवी"),
    "yajnaseni-pratibha-ray": ("यज्ञसेनी", "प्रतिभा राय"),
    "shilapadma-pratibha-ray": ("शिलापद्म", "प्रतिभा राय"),
    "uttarmarg-pratibha-ray": ("उत्तमार्ग", "प्रतिभा राय"),
    "mahamoha-pratibha-ray": ("महामोह", "प्रतिभा राय"),
    "paraja-gopinath-mohanty": ("पराजा", "गोपीनाथ मोहंती"),
    "danapani-gopinath-mohanty": ("दानपानी", "गोपीनाथ मोहंती"),
    "dadibudha-gopinath-mohanty": ("दादीबुधा", "गोपीनाथ मोहंती"),
    "sei-somoy-sunil-gangopadhyay": ("सेई समय", "सुनील गंगोपाध्याय"),
    "aranyer-din-ratri-sunil-gangopadhyay": ("अरण्येर दिन रात्रि", "सुनील गंगोपाध्याय"),
    "prothom-alo-sunil-gangopadhyay": ("प्रथम आलो", "सुनील गंगोपाध्याय"),
    "purbo-paschim-sunil-gangopadhyay": ("पूर्बो पश्चिम", "सुनील गंगोपाध्याय"),
    "joi-baba-felunath-satyajit-ray": ("जय बाबा फेलुनाथ", "सत्यजित राय"),
    "sonar-kella-satyajit-ray": ("सोनार केल्ला", "सत्यजित राय"),
    "putul-nacher-itikatha-manik-bandyopadhyay": ("पुतुल नाचेर इतिकथा", "मानिक बंद्योपाध्याय"),
    "dibaratrir-kabya-manik-bandyopadhyay": ("दिबारात्रिर काव्य", "मानिक बंद्योपाध्याय"),
    "ghachar-ghochar-vivek-shanbhag": ("घचर घोचर", "विवेक शानभाग"),
    "datta-sarat-chandra-chattopadhyay": ("दत्ता", "शरतचंद्र चट्टोपाध्याय"),
    "grihadaha-sarat-chandra-chattopadhyay": ("गृहदाह", "शरतचंद्र चट्टोपाध्याय"),
    "jogajog-rabindranath-tagore": ("जोगाजोग", "रवींद्रनाथ ठाकुर"),
    "kalbela-samaresh-majumdar": ("कालबेला", "समरेश मजूमदार"),
    "uttaradhikar-samaresh-majumdar": ("उत्तराधिकार", "समरेश मजूमदार"),
    "ashani-sanket-bibhutibhushan-bandyopadhyay": ("आशनि संकेत", "बिभूतिभूषण बंद्योपाध्याय"),
    "adarsha-hindu-hotel-bibhutibhushan-bandyopadhyay": ("आदर्श हिंदू होटल", "बिभूतिभूषण बंद्योपाध्याय"),
    "ichhamati-bibhutibhushan-bandyopadhyay": ("इच्छामती", "बिभूतिभूषण बंद्योपाध्याय"),
    "belli-moda-triveni": ("बेल्लि मोद", "त्रिवेणी"),
    "apaswara-triveni": ("अपस्वर", "त्रिवेणी"),
    "mucchida-bagilu-triveni": ("मुच्चिद बागिलु", "त्रिवेणी"),
    "baanu-belagitu-triveni": ("बानु बेलगितु", "त्रिवेणी"),
    "keelu-gombe-triveni": ("कीलु गोम्बे", "त्रिवेणी"),
    "tavareya-kola-triveni": ("तवरेय कोल", "त्रिवेणी"),
    "hoovu-hannu-triveni": ("हूवु हन्नु", "त्रिवेणी"),
    "hannele-chiguridaga-triveni": ("हन्नेले चिगुरिदग", "त्रिवेणी"),
    "doorada-betta-triveni": ("दूरद बेट्ट", "त्रिवेणी"),
    "modala-hejje-triveni": ("मोदल हेज्जे", "त्रिवेणी"),
    "avala-magalu-triveni": ("अवल मगळु", "त्रिवेणी"),
    "hrudaya-geetha-triveni": ("हृदय गीत", "त्रिवेणी"),
    "vasanthagana-triveni": ("वसंतगण", "त्रिवेणी"),
    "kankana-triveni": ("कंकण", "त्रिवेणी"),
    "apajaya-triveni": ("अपजय", "त्रिवेणी"),
    "benkiya-bale-t-r-subba-rao": ("बेंकिय बाले", "टी. आर. सुब्बाराव"),
    "gaali-maatu-t-r-subba-rao": ("गालि मातु", "टी. आर. सुब्बाराव"),
    "parisara-kathe-poornachandra-tejaswi": ("परिसर कथे", "पूरणचंद्र तेजस्वी"),
    "mayaloka-poornachandra-tejaswi": ("मायालोक", "पूरणचंद्र तेजस्वी"),
    "annana-nenapu-poornachandra-tejaswi": ("अण्णन नेनपु", "पूरणचंद्र तेजस्वी"),
    "karvalo-poornachandra-tejaswi": ("करवालो", "पूरणचंद्र तेजस्वी"),
    "mana-tumbida-madadi-m-k-indira": ("मन तुम्बिद मददि", "एम. के. इंदिरा"),
    "poorvapara-m-k-indira": ("पूर्वापर", "एम. के. इंदिरा"),
    "sadananda-m-k-indira": ("सदानंद", "एम. के. इंदिरा"),
    "hennina-akankshe-m-k-indira": ("हेन्निना आकांक्षे", "एम. के. इंदिरा"),
    "tungabhadra-m-k-indira": ("तुंगभद्रा", "एम. के. इंदिरा"),
    "navaratna-m-k-indira": ("नवरत्न", "एम. के. इंदिरा"),
    "noorondu-baagilu-m-k-indira": ("नूरोंदु बागिलु", "एम. के. इंदिरा"),
    "musuku-m-k-indira": ("मुसुकु", "एम. के. इंदिरा"),
    "shikharasurya-chandrashekhara-kambara": ("शिखरसूर्य", "चंद्रशेखर कंबार"),
    "hamsageethe-tarasu": ("हंसगीते", "तारासु"),
    "durgastamana-tarasu": ("दुर्गास्तमन", "तारासु"),
    "krauncha-pakshigalu-vaidehi": ("क्रौंच पक्षिगळु", "वैदेही"),
    "avadeshwari-shankar-mokashi-punekar": ("अवधेश्वरी", "शंकर मोकाशी पुणेकर"),
    "tabbaliyu-neenade-magane-s-l-bhyrappa": ("तब्बलियु नीनेदे मगने", "एस. एल. भैरप्पा"),
    "taledanda-girish-karnad": ("तलेदंड", "गिरीश कर्नाड"),
    "poonachi-perumal-murugan": ("पूनाचि", "पेरुमाल मुरुगन"),
    "alai-osai-kalki-krishnamurthy": ("अलै ओसै", "कल्कि कृष्णमूर्ति"),
    "yavana-rani-sandilyan": ("यवन रानी", "सांडिल्यन"),
    "uthara-kaandam-rajam-krishnan": ("उत्तर कांडम्", "राजम कृष्णन"),
    "anithavin-kadhalgal-sujatha": ("अनिताविन् कादल्गळ", "सुजाता"),
    "ayiraththil-iruvar-sujatha": ("आयिरत्तिल इरुवर", "सुजाता"),
    "oru-naduppagal-maranam-sujatha": ("ओरु नडुप्पगल् मरणम्", "सुजाता"),
    "unnai-kanda-neramellam-sujatha": ("उन्नै कंड नेरमेल्लम्", "सुजाता"),
    "ganesh-x-vasanth-sujatha": ("गणेश वसंत", "सुजाता"),
    "irul-varum-neram-sujatha": ("इरुल् वरुम् नेरम्", "सुजाता"),
    "ethaiyum-oru-murai-sujatha": ("एतैयुम् ओरु मुरै", "सुजाता"),
    "aerakkuraiya-sorkkam-sujatha": ("एरक्कुरैय सोर्क्कम्", "सुजाता"),
    "aatma-gowravam-yaddanapudi-sulochana-rani": ("आत्म गौरवम्", "यड्डनपुडि सुलोचना रानी"),
    "jeevana-tarangalu-yaddanapudi-sulochana-rani": ("जीवन तरंगलु", "यड्डनपुडि सुलोचना रानी"),
    "girija-kalyanam-yaddanapudi-sulochana-rani": ("गिरिजा कल्याणम्", "यड्डनपुडि सुलोचना रानी"),
    "abhijata-yaddanapudi-sulochana-rani": ("अभिजात", "यड्डनपुडि सुलोचना रानी"),
    "vijeta-yaddanapudi-sulochana-rani": ("विजेता", "यड्डनपुडि सुलोचना रानी"),
    "jai-jawan-yaddanapudi-sulochana-rani": ("जय जवान", "यड्डनपुडि सुलोचना रानी"),
    "madhura-swapnam-yaddanapudi-sulochana-rani": ("मधुर स्वप्नम्", "यड्डनपुडि सुलोचना रानी"),
    "hrudaya-ganam-yaddanapudi-sulochana-rani": ("हृदय गानम्", "यड्डनपुडि सुलोचना रानी"),
    "prema-deepika-yaddanapudi-sulochana-rani": ("प्रेम दीपिका", "यड्डनपुडि सुलोचना रानी"),
    "priya-sakhi-yaddanapudi-sulochana-rani": ("प्रिय सखी", "यड्डनपुडि सुलोचना रानी"),
    "aradhana-yaddanapudi-sulochana-rani": ("आराधना", "यड्डनपुडि सुलोचना रानी"),
    "radha-krishna-yaddanapudi-sulochana-rani": ("राधा कृष्ण", "यड्डनपुडि सुलोचना रानी"),
    "amara-hridayam-yaddanapudi-sulochana-rani": ("अमर हृदयम्", "यड्डनपुडि सुलोचना रानी"),
    "keerti-kireetalu-yaddanapudi-sulochana-rani": ("कीर्ति किरीटलु", "यड्डनपुडि सुलोचना रानी"),
    "peddalaku-matrame-malladi-venkata-krishna-murthy": ("पेद्दलकु मात्रमे", "मल्लदि वेंकट कृष्ण मूर्ति"),
    "paanigrahanam-malladi-venkata-krishna-murthy": ("पाणिग्रहणम्", "मल्लदि वेंकट कृष्ण मूर्ति"),
    "vaikunthapu-yatra-malladi-venkata-krishna-murthy": ("वैकुंठपु यात्रा", "मल्लदि वेंकट कृष्ण मूर्ति"),
    "tenetiga-malladi-venkata-krishna-murthy": ("तेनेतिग", "मल्लदि वेंकट कृष्ण मूर्ति"),
    "shanivaaram-naadi-malladi-venkata-krishna-murthy": ("शनिवारम् नाडी", "मल्लदि वेंकट कृष्ण मूर्ति"),
    "abhilasha-yandamuri-veerendranath": ("अभिलाषा", "यंडमूरि वीरेंद्रनाथ"),
    "rendu-rella-aaru-yandamuri-veerendranath": ("रेंडु रेल्ल आरु", "यंडमूरि वीरेंद्रनाथ"),
    "antarmukham-yandamuri-veerendranath": ("अंतर्मुखम्", "यंडमूरि वीरेंद्रनाथ"),
    "tulasi-dalam-yandamuri-veerendranath": ("तुलसी दळम्", "यंडमूरि वीरेंद्रनाथ"),
    "pakudu-rallu-ravuri-bharadwaja": ("पकुडु रल्लु", "रावूरि भारद्वाज"),
    "daivam-ichina-bharya-chalam": ("दैवम् इचिना भार्या", "चालम"),
    "modugu-poolu-dasarathi-rangacharya": ("मोडुगु पूलु", "दासरथी रंगाचार्य"),
    "delhi-gadhakal-m-mukundan": ("दिल्ली गधाकळ", "एम. मुकुंदन"),
    "ntuppuppakkoranendarnnu-vaikom-muhammad-basheer": ("न्तुप्पुप्पक्कोरानेन्दार्न्नु", "वैकम मुहम्मद बशीर"),
    "k-t-n-kottoor-ezhuthum-jeevithavum-t-p-rajeevan": ("के. टी. एन. कोट्टूर", "टी. पी. राजिवन"),
    "abhayarthikal-anand": ("अभयार्थिकळ", "आनंद"),
    "aalkkoottam-anand": ("आल्क्कूट्टम्", "आनंद"),
    "yugandhar-shivaji-sawant": ("युगंधर", "शिवाजी सावंत"),
    "ghashiram-kotwal-vijay-tendulkar": ("घाशीराम कोतवाल", "विजय तेंडुलकर"),
    "sambhaji-vishwas-patil": ("संभाजी", "विश्वास पाटील"),
    "cobalt-blue-sachin-kundalkar": ("कोबाल्ट ब्लू", "सचिन कुंदलकर"),
    "priyajan-vinesh-antani": ("प्रियजन", "विनेश अंतानी"),
    "kuvo-ashokpuri-goswami": ("कुवो", "अशोकपुरी गोस्वामी"),
    "chander-pahar-bibhutibhushan-bandyopadhyay": ("चंदर पहाड़", "बिभूतिभूषण बंद्योपाध्याय"),
    "arogyaniketan-tarashankar-bandyopadhyay": ("आरोग्यनिकेतन", "ताराशंकर बंद्योपाध्याय"),
    "kabi-tarashankar-bandyopadhyay": ("कवि ताराशंकर", "ताराशंकर बंद्योपाध्याय"),
    "saatkahon-samaresh-majumdar": ("सातकाहोन", "समरेश मजूमदार"),
    "manojdasank-katha-o-kahini-manoj-das": ("कथा ओ कहिनी", "मनोज दास"),
    "aakashra-isara-manoj-das": ("आकाशर इसारा", "मनोज दास"),
    "dhumabha-diganta-manoj-das": ("धूमभा दिगंत", "मनोज दास"),
    "amruta-phala-manoj-das": ("अमृत फल", "मनोज दास"),
    "mamu-fakir-mohan-senapati": ("मामु", "फकीर मोहन सेनापति"),
    "chaturanga-rabindranath-tagore": ("चतुरंग", "रवींद्रनाथ ठाकुर"),
    "noukadubi-rabindranath-tagore": ("नौकाडुबि", "रवींद्रनाथ ठाकुर"),
    "green-card-malladi-venkata-krishna-murthy": ("ग्रीन कार्ड", "मल्लदि वेंकट कृष्ण मूर्ति"),
    "secretary-yaddanapudi-sulochana-rani": ("सेक्रेटरी", "यड्डनपुडि सुलोचना रानी"),
    "sweet-revenge-malladi-venkata-krishna-murthy": ("स्वीट रिवेंज", "मल्लदि वेंकट कृष्ण मूर्ति"),
    "practical-joker-malladi-venkata-krishna-murthy": ("प्रैक्टिकल जोकर", "मल्लदि वेंकट कृष्ण मूर्ति"),
    "missing-malladi-venkata-krishna-murthy": ("मिसिंग", "मल्लदि वेंकट कृष्ण मूर्ति"),
    "the-eighteenth-parallel-ashokamitran": ("अठारहवीं समांतर", "अशोकमित्रन"),
    "new-bombay-tailors-mohammed-khadeer-babu": ("न्यू बॉम्बे टेलर्स", "मोहम्मद खादीर बाबू"),
    "no-presents-please-jayant-kaikini": ("नो प्रेजेंट्स प्लीज", "जयंत कायकिनी"),
    "francis-itty-cora-t-d-ramakrishnan": ("फ्रांसिस इट्टी कोरा", "टी. डी. रामकृष्णन"),
    "higuita-n-s-madhavan": ("हिगुइता", "एन. एस. माधवन"),
    "ave-maria-k-r-meera": ("आवे मारिया", "के. आर. मीरा"),
    "avasthe-u-r-ananthamurthy": ("अवस्थे", "यू. आर. अनंतमूर्ति"),
    "bhava-u-r-ananthamurthy": ("भाव", "यू. आर. अनंतमूर्ति"),
    "grihabhanga-s-l-bhyrappa": ("गृहभंग", "एस. एल. भैरप्पा"),
    "kanooru-heggadithi-kuvempu": ("कानूरु हेग्गदिति", "कुवेम्पु"),
    "raktha-raatri-t-r-subba-rao": ("रक्त रात्रि", "टी. आर. सुब्बाराव"),
    "chandanada-gombe-t-r-subba-rao": ("चंदनद गोम्बे", "टी. आर. सुब्बाराव"),
    "ambarada-apsare-m-k-indira": ("अंबरद अप्सरे", "एम. के. इंदिरा"),
    "giribale-m-k-indira": ("गिरिबाले", "एम. के. इंदिरा"),
    "mukti-triveni": ("मुक्ति त्रिवेणी", "त्रिवेणी"),
    "sotu-geddavalu-triveni": ("सोटु गेद्दवळु", "त्रिवेणी"),
    "aramane-kum-veerabhadrappa": ("अरमने", "कुम. वीरभद्रप्पा"),
    "kudiyara-koosu-k-shivaram-karanth": ("कुडियार कूसु", "के. शिवराम कारंत"),
    "baduku-geeta-nagabhushan": ("बदुकु", "गीता नागभूषण"),
    "ammachiyemba-nenapu-vaidehi": ("अम्मचियेंब नेनपु", "वैदेही"),
    "solaimalai-ilavarasi-kalki-krishnamurthy": ("सोलैमलै इलवरसि", "कल्कि कृष्णमूर्ति"),
    "parthiban-kanavu-kalki-krishnamurthy": ("पार्थिबन कनवु", "कल्कि कृष्णमूर्ति"),
    "sila-nerangalil-sila-manithargal-d-jayakanthan": ("सिल नेरंगळिल सिल मनिदर्गळ", "जयकांतन"),
    "chembaruthi-t-janakiraman": ("चेंबरुति", "टी. जानकीरमन"),
    "mercury-pookkal-balakumaran": ("मर्करी पूक्कळ", "बालकुमारन"),
    "samuthaya-veedhi-na-parthasarathy": ("समुदाय वीदि", "ना. पार्थसारथी"),
    "puyalile-oru-thoni-p-singaram": ("पुयलिले ओरु तोणि", "पी. सिंगारम"),
    "gopalla-gramam-ki-rajanarayanan": ("गोपल्ल ग्रामम्", "की. राजनारायणन"),
    "oru-puliyamarathin-kathai-sundara-ramaswamy": ("ओरु पुलियमरत्तिन् कदै", "सुंदर रामस्वामी"),
    "vanmam-bama": ("वनमम्", "बामा"),
    "kayalvizhi-akilan": ("कयलविषि", "अकिलन"),
    "enge-pogiroam-akilan": ("एंगे पोगिरोम्", "अकिलन"),
    "mannan-magal-sandilyan": ("मन्नन मगळ", "सांडिल्यन"),
    "en-iniya-iyanthira-sujatha": ("एन इनिय इयंत्र", "सुजाता"),
    "meena-yaddanapudi-sulochana-rani": ("मीना", "यड्डनपुडि सुलोचना रानी"),
    "chandipriya-yaddanapudi-sulochana-rani": ("चंडिप्रिया", "यड्डनपुडि सुलोचना रानी"),
    "aahuti-yaddanapudi-sulochana-rani": ("आहुति", "यड्डनपुडि सुलोचना रानी"),
    "thommidi-ghantalu-malladi-venkata-krishna-murthy": ("तोम्मिदि घंटलु", "मल्लदि वेंकट कृष्ण मूर्ति"),
    "dooram-malladi-venkata-krishna-murthy": ("दूरम्", "मल्लदि वेंकट कृष्ण मूर्ति"),
    "andamaina-jeevitam-malladi-venkata-krishna-murthy": ("अंदमैन जीवितम्", "मल्लदि वेंकट कृष्ण मूर्ति"),
    "yagnam-kalipatnam-ramarao": ("यज्ञम्", "कलिपत्नम् रामाराव"),
    "athadu-adavini-jayinchadu-kesava-reddy": ("अतडु अदविनि जयिंचडु", "केशव रेड्डी"),
    "manodharmaparagam-madhurantakam-narendra": ("मनोधर्मपरागम्", "मधुरान्तकम् नरेंद्र"),
    "govardhanante-yathrakal-anand": ("गोवर्धनन्टे यात्राकळ", "आनंद"),
    "marubhoomikal-undakunnathu-anand": ("मरुभूमिकळ उंडकुन्नतु", "आनंद"),
    "ormayude-arakal-vaikom-muhammad-basheer": ("ओर्मयुडे अरकळ", "वैकम मुहम्मद बशीर"),
    "balyakalasakhi-vaikom-muhammad-basheer": ("बाल्यकालसखी", "वैकम मुहम्मद बशीर"),
    "nritham-m-mukundan": ("नृत्तम्", "एम. मुकुंदन"),
    "mayyazhippuzhayude-theerangalil-m-mukundan": ("मय्यषिप्पुषयुडे तीरंगळिल", "एम. मुकुंदन"),
    "qabar-k-r-meera": ("कब्र", "के. आर. मीरा"),
    "manushyanu-oru-aamukham-subhash-chandran": ("मनुष्यनु ओरु आमुखम्", "सुभाष चंद्रन"),
    "gurusagaram-o-v-vijayan": ("गुरुसागरम्", "ओ. वी. विजयन"),
    "vishakanyaka-s-k-pottekkatt": ("विषकन्यका", "एस. के. पोट्टेक्काट"),
    "oru-sankeerthanam-pole-perumbadavam-sreedharan": ("ओरु संकीर्तनम् पोले", "पेरुम्பாடवम् श्रीधरन"),
    "meesha-s-hareesh": ("मीशा", "एस. हरीश"),
    "ram-c-o-anandhi-akhil-p-dharmajan": ("राम सी ओ आनंदी", "अखिल पी. धर्मजन"),
    "chhava-shivaji-sawant": ("छावा", "शिवाजी सावंत"),
    "jhool-bhalchandra-nemade": ("झूल", "भाळचंद्र नेमाडे"),
    "shriman-yogi-ranjit-desai": ("श्रीमान योगी", "रणजीत देसाई"),
    "sakharam-binder-vijay-tendulkar": ("सखाराम बाइंडर", "विजय तेंडुलकर"),
    "upara-laxman-mane": ("उपरा", "लक्ष्मण माने"),
    "jay-somnath-k-m-munshi": ("जय सोमनाथ", "कन्हैयालाल माणिकलाल मुंशी"),
    "chauladevi-dhumketu": ("चौलादेवी", "धूमकेतु"),
    "janamtip-ishwar-petlikar": ("जनमटीप", "ईश्वर पेटलीकर"),
    "dariyalal-gunvantrai-acharya": ("दरियालाल", "गुणवंतराय आचार्य"),
    "ansar-varsha-adalja": ("अंसार", "वर्षा अडालजा"),
    "pather-dabi-sarat-chandra-chattopadhyay": ("पथेर दाबि", "शरतचंद्र चट्टोपाध्याय"),
    "kapalkundala-bankim-chandra-chattopadhyay": ("कपालकुंडला", "बंकिम चंद्र चट्टोपाध्याय"),
    "krishnakanter-will-bankim-chandra-chattopadhyay": ("कृष्णकांतेर विल", "बंकिम चंद्र चट्टोपाध्याय"),
    "shesher-kabita-rabindranath-tagore": ("शेषेर कविता", "रवींद्रनाथ ठाकुर"),
    "padma-nadir-majhi-manik-bandyopadhyay": ("पद्मा नदीर माझि", "मानिक बंद्योपाध्याय"),
    "chha-mana-atha-guntha-fakir-mohan-senapati": ("छ मन आठ गुंठ", "फकीर मोहन सेनापति"),
    "ajibakara-attahasa-surendra-mohanty": ("अजिबकर अट्टहास", "सुरेंद्र मोहंती"),
    "krushnavenire-sandhya-surendra-mohanty": ("कृष्णवेणीरे संध्या", "सुरेंद्र मोहंती"),
    "maharani-putra-pratibha-ray": ("महारानी पुत्र", "प्रतिभा राय"),
    "vennello-aadapilla-yandamuri-veerendranath": ("वेन्नेल्लो आडपिल्ला", "यंडमूरि वीरेंद्रनाथ"),
    "vekkai-poomani": ("वेक्कै", "पूमणि"),
    "shabdangal-vaikom-muhammad-basheer": ("शब्दंगळ", "वैकम मुहम्मद बशीर"),
    "donga-police-malladi-venkata-krishna-murthy": ("डोंगा पुलिस", "मल्लदि वेंकट कृष्ण मूर्ति"),
    "aatmiyulu-yaddanapudi-sulochana-rani": ("आत्मीयुलु", "यड्डनपुडि सुलोचना रानी"),
    "marappasu-t-janakiraman": ("मराप्पशु", "टी. जानकीरमन"),
    "jaala-m-k-indira": ("जाला", "एम. के. इंदिरा"),
    "pudu-vellam-akilan": ("पुदु वेल्लम्", "अकिलन"),
    "evariki-cheppaka-malladi-venkata-krishna-murthy": ("एवरिकी चेप्पका", "मल्लदि वेंकट कृष्ण मूर्ति"),
    "alaivaai-karaiyile-rajam-krishnan": ("अलैवाय करैयिले", "राजम कृष्णन"),
    "soorpanakha-k-r-meera": ("शूर्पणखा", "के. आर. मीरा"),
    "college-boy-surendra-mohanty": ("कॉलेज बॉय", "सुरेंद्र मोहंती"),
    "mogali-rekulu-yaddanapudi-sulochana-rani": ("मोगलि रेकुलु", "यड्डनपुडि सुलोचना रानी"),
    "mella-mella-sivasankari": ("मेल्ला मेल्ला", "शिवसंकरी"),
    "hindu-jagnyachi-samruddha-adgal-bhalchandra-nemade": ("हिंदू जगण्याची समृद्ध अडगळ", "भाळचंद्र नेमाडे"),
    "vyasanum-vighneswaranum-anand": ("व्यासनुम् विघ्नेश्वरनुम्", "आनंद"),
    "kalpurush-samaresh-majumdar": ("कल्पुरुष", "समरेश मजूमदार"),
    "majya-jalmachi-chittarkatha-shantabai-kamble": ("माझ्या जन्माची चित्तरकथा", "शांताबाई कांबळे"),
    "kayar-thakazhi-sivasankara-pillai": ("कयर", "तकषि शिवशंकर पिल्लै"),
    "liludi-dharati-chunilal-madia": ("लीलुडी धरती", "चुनीलाल मडिया"),
    "odaathe-sujatha": ("ओडाते", "सुजाता"),
    "ame-badha-jyotindra-dave-and-dhansukhlal-mehta": ("अमे बधा", "ज्योतिंद्र दवे"),
    "irumbu-kuthiraigal-balakumaran": ("इरुम्बु कुतिरैगळ", "बालकुमारन"),
    "keelubommalu-g-v-krishna-rao": ("कीलुबोम्मलु", "जी. वी. कृष्ण राव"),
    "karunaikolai-sivasankari": ("करुणैकोलै", "शिवसंकरी"),
    "sharapanjara-triveni": ("शरपंजरा", "त्रिवेणी"),
    "daivathinte-vikrithikal-m-mukundan": ("दैवत्तिन्टे विकृतिगळ", "एम. मुकुंदन"),
    "asuravithu-m-t-vasudevan-nair": ("असुरवितु", "एम. टी. वासुदेवन नायर"),
    "manvi-ni-bhavai-pannalal-patel": ("मानवी नी भवई", "पन्नालाल पटेल"),
    "harijana-gopinath-mohanty": ("हरिजन", "गोपीनाथ मोहंती"),
    "gram-lakshmi-ramanlal-vasantlal-desai": ("ग्रामलक्ष्मी", "रमणलाल वसंतलाल देसाई"),
    "asa-mi-asami-p-l-deshpande": ("असा मी असामी", "पु. ल. देशपांडे"),
    "premalekhanam-vaikom-muhammad-basheer": ("प्रेमलेखनम्", "वैकम मुहम्मद बशीर"),
    "karan-ghelo-nandshankar-mehta": ("करण घेलो", "नंदशंकर मेहता"),
    "ayirankalathu-payir-sivasankari": ("आयिरंकालत्तु पयिर", "शिवसंकरी"),
    "chantabbai-malladi-venkata-krishna-murthy": ("चंतब्बाइ", "मल्लदि वेंकट कृष्ण मूर्ति"),
    "rahura-chhaya-gopinath-mohanty": ("राहुर छाया", "गोपीनाथ मोहंती"),
    "mullappoo-niramulla-pakalukal-benyamin": ("मुल्लप्पू निरमुळ्ळ पकलुकळ", "बिन्यामीन"),
    "kiragoorina-gayyaligalu-poornachandra-tejaswi": ("किरगूरिन गय्याळिगळु", "पूरणचंद्र तेजस्वी"),
    "bidhar-bhalchandra-nemade": ("बिढार", "भाळचंद्र नेमाडे"),
    "manojpancabimsati-manoj-das": ("मनोज पंचविंशति", "मनोज दास"),
    "amrutara-santana-gopinath-mohanty": ("अमृतरा संतान", "गोपीनाथ मोहंती"),
    "kashiyatre-triveni": ("काशीयात्रे", "त्रिवेणी"),
    "andha-diganta-surendra-mohanty": ("अंध दिगंत", "सुरेंद्र मोहंती"),
    "prema-lekhalu-yaddanapudi-sulochana-rani": ("प्रेम लेखलु", "यड्डनपुडि सुलोचना रानी"),
    "matadana-s-l-bhyrappa": ("मतदान", "एस. एल. भैरप्पा"),
    "niladri-vijaya-surendra-mohanty": ("नीलाद्रि विजय", "सुरेंद्र मोहंती"),
    "yanthram-malayattoor-ramakrishnan": ("यंत्रम्", "मलयाट्टूर रामकृष्णन"),
    "avala-mane-triveni": ("अवळ मने", "त्रिवेणी"),
    "eppothum-pen-sujatha": ("एप्पोदुम् पेण", "सुजाता"),
    "randamoozham-m-t-vasudevan-nair": ("रंडमूषम्", "एम. टी. वासुदेवन नायर"),
    "koomankolli-p-vatsala": ("कूमन्कोल्लि", "पी. वत्सला"),
    "patan-ni-prabhuta-k-m-munshi": ("पतन नी प्रभुता", "कन्हैयालाल माणिकलाल मुंशी"),
    "oru-manithan-oru-veedu-oru-ulagam-d-jayakanthan": ("ओरु मनिदन ओरु वीडु ओरु उलगम्", "जयकांतन"),
    "nila-saila-surendra-mohanty": ("नील शैल", "सुरेंद्र मोहंती"),
    "samudrantike-dhruv-bhatt": ("समुद्रांतिके", "ध्रुव भट्ट"),
    "shesh-prashna-sarat-chandra-chattopadhyay": ("शेष प्रश्न", "शरतचंद्र चट्टोपाध्याय"),
    "narayana-rao-adavi-bapiraju": ("नारायण राव", "अदवि बापिराजु"),
    "akoopar-dhruv-bhatt": ("अकूपार", "ध्रुव भट्ट"),
    "sangati-bama": ("संगति", "बामा"),
    "karaiyellam-shenbagapoo-sujatha": ("करैयेल्लाम् शेनबगापू", "सुजाता"),
    "apahancha-gopinath-mohanty": ("अपहंच", "गोपीनाथ मोहंती"),
    "malela-jeev-pannalal-patel": ("मलेला जीव", "पन्नालाल पटेल"),
    "mana-gahirara-chasa-gopinath-mohanty": ("मन गहिरर चास", "गोपीनाथ मोहंती"),
    "hool-bhalchandra-nemade": ("हूळ", "भाळचंद्र नेमाडे"),
    "pulayathara-paul-chirakkarode": ("पुलयतारा", "पॉल चिरक्करोडे"),
    "bekkina-kannu-triveni": ("बेक्किन कन्नु", "त्रिवेणी"),
    "vevishal-zaverchand-meghani": ("वेविशाल", "झवेरचंद मेघाणी"),
    "aalahayude-penmakkal-sarah-joseph": ("आलहायुडे पेणमक्कळ", "सारा जोसेफ"),
    "aalohari-anandam-sarah-joseph": ("आलोहारि आनंदम्", "सारा जोसेफ"),
    "badshahi-angti-satyajit-ray": ("बादशाही आंग्टि", "सत्यजित राय"),
    "madhuvana-m-k-indira": ("मधुवन", "एम. के. इंदिरा"),
    "odalaala-devanur-mahadeva": ("ओदलाळ", "देवनूर महादेव"),
    "dharmaraja-c-v-raman-pillai": ("धर्मराज", "सी. वी. रामन पिल्लै"),
    "otran-ashokamitran": ("ओट्रन", "अशोकमित्रन"),
    "aavarana-s-l-bhyrappa": ("आवरण", "एस. एल. भैरप्पा"),
    "thiruthu-n-s-madhavan": ("तिरुत्तु", "एन. एस. माधवन"),
    "swami-ranjit-desai": ("स्वामी", "रणजीत देसाई"),
    "natrang-anand-yadav": ("नटरंग", "आनंद यादव"),
    "shesha-basantara-chithi-manoj-das": ("शेष बसंतर चिट्ठी", "मनोज दास"),
    "maha-prasthanam-sri-sri": ("महाप्रस्थानम्", "श्री श्री"),
    "amrita-raghuveer-chaudhari": ("अमृता", "रघुवीर चौधरी"),
    "dhundhabhari-khin-vinesh-antani": ("धुंधभारी खीण", "विनेश अंताणी"),
    "ujavya-sondechya-bahulya-praveen-dashrath-bandekar": ("उजव्या सोंडेच्या बाहुल्या", "प्रवीण दशरथ बांदेकर"),
    "vilapayathra-m-t-vasudevan-nair": ("विलापयात्रा", "एम. टी. वासुदेवन नायर"),
    "aanavariyum-ponkurishum-vaikom-muhammad-basheer": ("आनवरियुम् पोंकुरिशुम्", "वैकम मुहम्मद बशीर"),
    "adityanum-radhayum-mattu-chilarum-m-mukundan": ("आदित्यनुम् राधयुम् मट्टु चिलरुम्", "एम. मुकुंदन"),
    "vishwavikhyathamaya-mookku-vaikom-muhammad-basheer": ("विश्वविख्यातमय मूक्कु", "वैकम मुहम्मद बशीर"),
    "lanthan-batheriyile-luthiniyakal-n-s-madhavan": ("लंतन बतेरियिले लुतिनियकळ", "एन. एस. माधवन"),
    "prajala-manishi-vattikota-alwar-swamy": ("प्रजला मनिषि", "वट्टिकोट अल्वर स्वामी"),
    "punyatoya-pratibha-ray": ("पुण्यतोया", "प्रतिभा राय"),
    "jeevana-samaram-ravuri-bharadwaja": ("जीवन समरम्", "रावूरी भारद्वाज"),
    "rajadhiraj-k-m-munshi": ("राजाधिराज", "कन्हैयालाल माणिकलाल मुंशी"),
    "mahanayak-vishwas-patil": ("महानायक", "विश्वास पाटील"),
    "bhadrambhadra-ramanbhai-neelkanth": ("भद्रंभाद्र", "रमणभाई नीलकंठ"),
    "anitha-ilam-manaivi-sujatha": ("अनिता इलम मनैवि", "सुजाता"),
    "aagamana-yaddanapudi-sulochana-rani": ("आगमन", "यड्डनपुडि सुलोचना रानी"),
    "gharadiha-nityananda-mahapatra": ("घरडिहा", "नित्यानंद महापात्र"),
    "apsara-sujatha": ("अप्सरा", "सुजाता"),
    "nenchin-alaigal-akilan": ("नेन्चिन अलैगळ", "अकिलन"),
    "amma-please-enakkaga-sivasankari": ("अम्मा प्लीज एनक्काग", "शिवसंकरी"),
    "moogavani-pillanagrovi-kesava-reddy": ("मूगवनि पिल्लनग्रोवि", "केशव रेड्डी"),
    "karippu-manigal-rajam-krishnan": ("करिप्पु मणिगळ", "राजम कृष्णन"),
    "bandhu-o-priya-surendra-mohanty": ("बंधु ओ प्रिया", "सुरेंद्र मोहंती"),
    "hamsagitee-surendra-mohanty": ("हंसगीति", "सुरेंद्र मोहंती"),
    "aakasamlo-sagam-volga": ("आकाशम्लो सगम्", "वोल्गा"),
    "sakina-s-kiss-vivek-shanbhag": ("सकीनाज किस", "विवेक शानभाग"),
    "o-andhagali-akhilmohan-patnaik": ("ओ अंधगली", "अखिलमोहन पटनायक"),
    "varanasi-m-t-vasudevan-nair": ("वाराणसी", "एम. टी. वासुदेवन नायर"),
    "munemma-kesava-reddy": ("मुनेम्मा", "केशव रेड्डी"),
    "mayiladumkunnu-muttathu-varkey": ("मयिलाडुम्कुन्नु", "मुट्टात्तु वर्की"),
    "charitraheen-sarat-chandra-chattopadhyay": ("चरित्रहीन", "शरतचंद्र चट्टोपाध्याय"),
    "sapana-mati-gopinath-mohanty": ("सपन मटि", "गोपीनाथ मोहंती"),
    "neti-neti-surendra-mohanty": ("नेति नेति", "सुरेंद्र मोहंती"),
    "amrita-dhara-yaddanapudi-sulochana-rani": ("अमृत धारा", "यड्डनपुडि सुलोचना रानी"),
    "aa-maratheyum-marannu-marannu-njan-k-r-meera": ("आ मारातेयुम् मरन्नु मरन्नु जान", "के. आर. मीरा"),
    "dui-patra-gopinath-mohanty": ("दुइ पत्र", "गोपीनाथ मोहंती"),
    "budhini-sarah-joseph": ("बुधिनी", "सारा जोसेफ"),
    "dui-simanta-surendra-mohanty": ("दुइ सीमांत", "सुरेंद्र मोहंती"),
    "sibabhai-gopinath-mohanty": ("सिबभाई", "गोपीनाथ मोहंती"),
    "prayaschita-fakir-mohan-senapati": ("प्रायश्चित्त", "फकीर मोहन सेनापति"),
    "abhinetri-kanhucharan-mohanty": ("अभिनेत्री", "कांहूचरण मोहंती"),
    "amrutham-kurisina-ratri-devarakonda-balagangadhara-tilak": ("अमृतम् कुरिसिन रात्रि", "देवराकोंडा बालागंगाधर तिलक"),
    "47-naatkal-sivasankari": ("४७ नाट्कळ", "शिवसंकरी"),
    "chaka-bhaunri-kanhucharan-mohanty": ("चका भौंरी", "कांहूचरण मोहंती"),
    "nooleni-sivasankari": ("नूलेनि", "शिवसंकरी"),
    "malajanha-upendra-kishore-das": ("मलाजन्हा", "उपेंद्र किशोर दास"),
    "hrudaya-netri-malati-chendur": ("हृदय नेत्री", "मालती चेंदुर"),
    "mithunam-sriramana": ("मिथुनम्", "श्रीरमणा"),
    "kalarekhalu-ampasayya-naveen": ("कालरेखालु", "अम्पासय्या नवीन"),
    "abhisapta-gandharba-mohapatra-nilamani-sahoo": ("अभिशप्त गंधर्व", "महापात्र नीलमणि साहू"),
    "kurinji-then-rajam-krishnan": ("कुरिंजि तेन", "राजम कृष्णन"),
    "pen-akilan": ("पेण", "अकिलन"),
    "parichaya-pratibha-ray": ("परिचय", "प्रतिभा राय"),
    "verukku-neer-rajam-krishnan": ("वेरुक्कु नीर", "राजम कृष्णन"),
    "penn-kural-rajam-krishnan": ("पेण्ण कुरल्", "राजम कृष्णन"),
    "lachhama-fakir-mohan-senapati": ("लाछमा", "फकीर मोहन सेनापति"),
    "indulekha-o-chandu-menon": ("इंदुलेखा", "ओ. चंदु मेनोन"),
    "sthalathe-pradhana-divyan-vaikom-muhammad-basheer": ("स्थलत्ते प्रधान दिव्यन्", "वैकम मुहम्मद बशीर"),
    "krishnayan-kajal-oza-vaidya": ("कृष्णायन", "काजल ओझा वैद्य"),
    "poleramma-banda-kathalu-mohammed-khadeer-babu": ("पोलेरम्मा बंडा कथलु", "मोहम्मद खादीर बाबू"),
    "chivari-gudise-kesava-reddy": ("चिवरि गुडिसे", "केशव रेड्डी"),
    "kalantara-surendra-mohanty": ("कालांतर", "सुरेंद्र मोहंती"),
    "mathilukal-vaikom-muhammad-basheer": ("मथिलुकळ", "वैकम मुहम्मद बशीर"),
    "saratababunka-gali-gopinath-mohanty": ("शरतबाबुंकर गलि", "गोपीनाथ मोहंती"),
    "achalatana-surendra-mohanty": ("अचलतना", "सुरेंद्र मोहंती"),
    "paleri-manikyam-oru-pathirakolapathakathinte-katha-t-p-rajeevan": ("पलेरि माणिक्यम्", "टी. पी. राजीवन्"),
}

_DEV = re.compile(r"[\u0900-\u097F]")
_AUTHOR_TAKE = {
    "प्रेमचंद": 2, "प्रसाद": 2, "बच्चन": 3, "दिनकर": 3, "गुप्त": 2,
    "शुक्ल": 2, "वर्मा": 2, "राकेश": 2, "अज्ञेय": 1, "रेणु": 2,
    "यशपाल": 1, "भारती": 2, "निराला": 3, "पंत": 2, "द्विवेदी": 3,
    "नागार्जुन": 1, "साहनी": 2, "सिंह": 2, "त्रिपाठी": 3, "जोशी": 2,
    "राघव": 2, "सोबती": 2, "भंडारी": 2, "शर्मा": 2, "पाठक": 3,
    "खत्री": 2, "कोहली": 2, "विवेकानंद": 2, "सरस्वती": 3, "तुलसीदास": 2,
    "सूरदास": 1, "कबीर": 1, "जायसी": 3, "बिहारी": 1, "मीराबाई": 1,
    "हरिश्चंद्र": 2, "ठाकुर": 2, "टैगोर": 2, "यादव": 2, "चंदर": 2,
    "मुक्तिबोध": 2, "आचार्य": 2, "पुष्पा": 2, "शिवानी": 1, "संजीव": 1,
    "ज्ञानरंजन": 1, "वजाहत": 2, "बिस्मिल्लाह": 2, "प्रकाश": 2,
    "सांकृत्यायन": 2, "सांकृतयायन": 2, "पाण्डेय": 2, "पांडेय": 2,
    "नारायण": 2, "केदारनाथ": 1, "निरंजननाथ": 1, "चक्रधर": 2,
    "बंद्योपाध्याय": 2, "चट्टोपाध्याय": 2, "नागर": 2,
    "कम्बोज": 3, "शिवमूर्ति": 1, "कमलेश्वर": 1, "शास्त्री": 3,
}


def _slug_ascii(title: str, source: str = "") -> str:
    if source:
        core = re.sub(r"-(saransh|सारांश|hindi-summary)$", "", source, flags=re.I)
        if re.fullmatch(r"[a-z0-9-]+", core) and len(core) >= 4:
            return core[:80]
    if re.fullmatch(r"[a-z0-9-]+", title.lower().replace(" ", "-")):
        return re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")[:80]
    # light Devanagari → latin for filenames
    table = {
        "क": "k", "ख": "kh", "ग": "g", "घ": "gh", "ङ": "n",
        "च": "ch", "छ": "chh", "ज": "j", "झ": "jh", "ञ": "n",
        "ट": "t", "ठ": "th", "ड": "d", "ढ": "dh", "ण": "n",
        "त": "t", "थ": "th", "द": "d", "ध": "dh", "न": "n",
        "प": "p", "फ": "ph", "ब": "b", "भ": "bh", "म": "m",
        "य": "y", "र": "r", "ल": "l", "व": "v", "श": "sh",
        "ष": "sh", "स": "s", "ह": "h", "क्ष": "ksh", "त्र": "tr", "ज्ञ": "gy",
        "ा": "a", "ि": "i", "ी": "i", "ु": "u", "ू": "u", "े": "e", "ै": "ai",
        "ो": "o", "ौ": "au", "ं": "n", "ः": "", "्": "", "ँ": "n",
        "अ": "a", "आ": "aa", "इ": "i", "ई": "ee", "उ": "u", "ऊ": "oo",
        "ए": "e", "ऐ": "ai", "ओ": "o", "औ": "au", "ऋ": "ri",
    }
    out = []
    i = 0
    s = title
    while i < len(s):
        if s[i:i + 2] in table:
            out.append(table[s[i:i + 2]])
            i += 2
            continue
        ch = s[i]
        if ch in table:
            out.append(table[ch])
        elif ch.isalnum() and ord(ch) < 128:
            out.append(ch.lower())
        elif ch in " -_":
            out.append("-")
        i += 1
    slug = re.sub(r"-+", "-", "".join(out)).strip("-")[:80]
    return slug or "hindi-book"


_LATIN_AUTHORS = {
    "ved prakash sharma": "वेद प्रकाश शर्मा",
    "prakash sharma": "वेद प्रकाश शर्मा",
    "ved prakash kamboj": "वेद प्रकाश कम्बोज",
    "prakash kamboj": "वेद प्रकाश कम्बोज",
    "surender mohan pathak": "सुरेंद्र मोहन पाठक",
    "mohan pathak": "सुरेंद्र मोहन पाठक",
    "om prakash sharma": "ओम प्रकाश शर्मा",
}


def _dev_tokens(text: str) -> str:
    return " ".join(t for t in text.split() if _DEV.search(t))


def _latin_author(parts: list[str], leftover: str) -> str:
    toks = []
    for t in list(parts) + leftover.split():
        if re.fullmatch(r"[A-Za-z.]+", t) and t.lower() not in toks:
            toks.append(t.lower())
    blob = " ".join(toks).strip()
    if blob in _LATIN_AUTHORS:
        return _LATIN_AUTHORS[blob]
    for key, val in sorted(_LATIN_AUTHORS.items(), key=lambda kv: -len(kv[0])):
        if key in blob:
            return val
    return "अज्ञात"


def _split_hi_parts(parts: list[str]) -> tuple[str, str]:
    if not parts:
        return "अज्ञात", "अज्ञात"
    if len(parts) == 1:
        return parts[0], "अज्ञात"
    take = 2 if len(parts) >= 3 else 1
    last = parts[-1]
    if last in _AUTHOR_TAKE:
        take = min(_AUTHOR_TAKE[last], len(parts) - 1)
    take = min(max(take, 1), len(parts) - 1)
    title = " ".join(parts[:-take])
    author = " ".join(parts[-take:])
    return title or parts[0], author or "अज्ञात"


def parse_hindi_slug(raw: str) -> dict | None:
    """Parse /books/{slug}-saransh, -सारांश, -hindi-summary, or Devanagari slug."""
    s = unquote(raw.strip())
    s = re.sub(r"^https?://[^/]+/books/", "", s, flags=re.I)
    s = s.strip("/")
    s = re.sub(r"20\d{2}-\d{2}-\d{2}.*$", "", s)
    low = s.lower()
    is_hi = (
        "hindi-summary" in low
        or low.endswith("-saransh")
        or s.endswith("-सारांश")
        or bool(_DEV.search(s))
    )
    if not is_hi:
        return None
    # Drop English-only *-summary that isn't hindi-summary/saransh
    if low.endswith("-summary") and "hindi-summary" not in low and not _DEV.search(s):
        return None
    core = s
    for suf in ("-hindi-summary", "-saransh", "-सारांश", "-summary"):
        if core.lower().endswith(suf) or core.endswith(suf):
            core = core[: -len(suf)]
            break
    parts = [p for p in core.replace("_", "-").split("-") if p]
    if not parts:
        return None
    # Prefer known roman → Devanagari mapping
    ascii_try = re.sub(r"[^a-z0-9]+", "-", core.lower()).strip("-")
    for key, (t, a) in ROMAN_HI.items():
        if ascii_try == key or ascii_try.startswith(key + "-"):
            return {
                "title": t,
                "author": a,
                "category": "हिन्दी साहित्य",
                "slug": key,
                "source_slug": core,
                "lang": "hi",
            }
    is_hindi_summary = "hindi-summary" in low
    last = parts[-1]
    if is_hindi_summary and last not in _AUTHOR_TAKE:
        title, author = " ".join(parts), "अज्ञात"
    else:
        title, author = _split_hi_parts(parts)
    if _DEV.search(title + author) and re.search(r"[A-Za-z]", title + author):
        leftover = " ".join(t for t in (title + " " + author).split() if not _DEV.search(t))
        title = _dev_tokens(title) or title
        author_hi = _dev_tokens(author)
        author = author_hi if author_hi else _latin_author(parts, leftover)
    if not _DEV.search(title + author):
        roman_authors = (
            "premchand", "prasad", "bachchan", "dinkar", "agyeya", "nirala", "pant",
            "mahadevi", "shukla", "yashpal", "bharati", "renu", "sahni", "rakesh",
            "bhandari", "sobti", "verma", "nirmal", "tulsidas", "kabir", "tagore",
            "vivekanand", "dayanand", "dwivedi", "nagarjun", "namvar", "pathak",
            "khatri", "sankrityayan", "bachan",
        )
        if ascii_try not in ROMAN_HI and not any(a in (ascii_try or "") for a in roman_authors):
            return None
        title = title.replace("-", " ").strip().title()
        author = author.replace("-", " ").strip().title()
    slug = _slug_ascii(title, core)
    if len(slug) < 3:
        # Short title token (e.g. एक-ओंकार-सतनाम) — transliterate the full core.
        slug = _slug_ascii(core.replace("-", " "), "")
    if len(slug) < 3:
        return None
    cat = "हिन्दी साहित्य"
    blob = f"{title} {author} {core}"
    if re.search(r"पुराण|गीता|योग|उपनिषद|सूत्र|अध्यात्म|विवेक|भक्ति|रामचरित|कबीर", blob):
        cat = "दर्शन व अध्यात्म"
    elif re.search(r"इतिहास|यात्रा|जीवनी|आत्मकथा", blob):
        cat = "इतिहास" if "यात्रा" in blob or "इतिहास" in blob else "जीवनी"
    elif re.search(r"हतया|हत्या|खून|गुंडा|जासूस|pathak|शर्मा", blob, re.I):
        cat = "रहस्य व थ्रिलर"
    else:
        guessed = guess_category(title, core)
        if guessed != "General":
            cat = guessed
    return {
        "title": title,
        "author": author or "अज्ञात",
        "category": cat,
        "slug": slug[:80],
        "source_slug": core,
        "lang": "hi",
    }


def _title_key(title: str) -> str:
    return re.sub(r"[\s:।,\.]+", "", (title or "")).strip()


def load_hindi_books(slugs_file: str | None = None) -> list[dict]:
    seen: set[str] = set()
    seen_titles: set[str] = set()
    books: list[dict] = []
    for title, author, category, slug in HINDI_SEED:
        if slug in seen:
            continue
        seen.add(slug)
        seen_titles.add(_title_key(title))
        books.append({
            "title": title,
            "author": author,
            "category": category,
            "slug": slug,
            "lang": "hi",
        })
    raws: list[str] = []
    data_dir = HERE / "data"
    paths = []
    if slugs_file:
        paths.append(Path(slugs_file))
    if data_dir.is_dir():
        paths.extend(sorted(data_dir.glob("hindi*.txt")))
    for path in paths:
        if path.exists():
            raws.extend(path.read_text(encoding="utf-8").splitlines())
    for raw in raws:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        item = parse_hindi_slug(line if ("summary" in line.lower() or "saransh" in line.lower() or "सारांश" in line) else f"{line}-saransh")
        if not item or item["slug"] in seen:
            continue
        tk = _title_key(item["title"])
        if tk and tk in seen_titles:
            continue
        seen.add(item["slug"])
        if tk:
            seen_titles.add(tk)
        books.append(item)
    return books
