#!/usr/bin/env node
/**
 * Upload validated book files to Supabase. Two modes, same mapping as the app's
 * Admin > Bulk Upload parser (SUMMARY -> overview, AUDIO_SCRIPT -> deep_analysis, ...).
 *
 *   A) Direct API (recommended for bulk, resumable, idempotent):
 *        SUPABASE_URL=https://<ref>.supabase.co SUPABASE_SERVICE_ROLE_KEY=... \
 *        node scripts/bookfactory/upload.cjs content-drafts/en [--publish] [--limit N] [--dry-run]
 *
 *   B) SQL file to paste into the Supabase SQL Editor (no keys needed):
 *        node scripts/bookfactory/upload.cjs content-drafts/en --sql out.sql [--publish]
 *
 * Safety rules:
 *   - Only files that pass check.cjs (>= 3200 words, score >= 98) are uploaded.
 *   - Upsert on slug, so re-running never duplicates; it refreshes the text.
 *   - Books land as drafts (is_draft = true) unless --publish is given.
 *   - The service-role key is read from the environment only. Never commit it.
 */
const fs = require('fs');
const path = require('path');
const { validate, parseBookFile, listBookFiles, wordCount, GENRE_COVER, PROSE_SECTIONS, similarity } = require('./lib.cjs');

const args = process.argv.slice(2);
const flag = (n) => args.includes(n);
const opt = (n, d) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : d; };
const dir = path.resolve(args.find((a) => !a.startsWith('--') && a !== opt('--sql') && a !== opt('--limit')) || path.join(__dirname, '..', '..', 'content-drafts', 'en'));
const publish = flag('--publish');
const dry = flag('--dry-run');
const sqlOut = opt('--sql');
const limit = Number(opt('--limit', '0')) || Infinity;
const BATCH = 10;

function toRow(file) {
  const raw = fs.readFileSync(file, 'utf8');
  const v = validate(raw);
  if (!v.pass) return { file, error: `failed quality gate (score ${v.score}, ${v.words} words): ${v.issues.filter((i) => i.hard).map((i) => i.msg).join('; ')}` };
  const { header, sections } = parseBookFile(raw);
  const total = Object.keys(PROSE_SECTIONS).reduce((a, k) => a + wordCount(sections[k]), 0);
  const isHi = /^hi/i.test(header.language);
  const row = {
    slug: header.slug,
    seo_slug: header.slug,
    title: header.title,
    author: header.author,
    category: header.category,
    cover_color: GENRE_COVER[header.genre] || 'amber',
    tagline: sections.HOOK,
    overview: sections.SUMMARY,
    key_ideas: sections.KEY_INSIGHTS,
    daily_application: sections.APPLY_TODAY,
    reflection_questions: sections.REFLECTION,
    action_system: sections.ACTION_SYSTEM,
    deep_analysis: sections.AUDIO_SCRIPT,
    language: isHi ? 'hi' : 'en',
    reading_time: Math.max(8, Math.ceil(total / 200)),
    year: /^-?\d+$/.test(header.year) ? Number(header.year) : null,
    meta_title: header.metatitle,
    meta_description: header.metadescription,
    seo_keywords: header.keywords.split(',').map((k) => k.trim()).filter(Boolean),
    is_draft: !publish,
    status: 'done',
  };
  const assets = {
    quiz_data: JSON.parse(sections.QUIZ_JSON),
    flashcard_data: JSON.parse(sections.FLASHCARDS_JSON),
    status: 'published',
  };
  return { file, row, assets, words: total };
}

// ----- SQL mode -------------------------------------------------------------
const dq = (s) => {
  let tag = 'bk';
  while (String(s).includes(`$${tag}$`)) tag += 'x';
  return `$${tag}$${s}$${tag}$`;
};
const lit = (v) => (v === null || v === undefined ? 'NULL' : typeof v === 'number' ? String(v) : typeof v === 'boolean' ? (v ? 'true' : 'false') : dq(v));
function toSql(items) {
  const cols = ['slug', 'seo_slug', 'title', 'author', 'category', 'cover_color', 'tagline', 'overview', 'key_ideas', 'daily_application', 'reflection_questions', 'action_system', 'deep_analysis', 'language', 'reading_time', 'year', 'meta_title', 'meta_description', 'seo_keywords', 'is_draft', 'status'];
  const out = ['-- Generated by scripts/bookfactory/upload.cjs. Safe to re-run (upsert on slug).', 'BEGIN;'];
  for (const { row, assets } of items) {
    const vals = cols.map((c) => (c === 'seo_keywords' ? `ARRAY[${row.seo_keywords.map(lit).join(',')}]::text[]` : lit(row[c])));
    const upd = cols.filter((c) => c !== 'slug').map((c) => `${c} = EXCLUDED.${c}`).join(', ');
    out.push(`-- ${row.title}`);
    out.push(`INSERT INTO public.books (${cols.join(', ')}) VALUES (${vals.join(', ')}) ON CONFLICT (slug) DO UPDATE SET ${upd};`);
    out.push(`INSERT INTO public.book_assets (book_id, quiz_data, flashcard_data, status) SELECT id, ${dq(JSON.stringify(assets.quiz_data))}::jsonb, ${dq(JSON.stringify(assets.flashcard_data))}::jsonb, 'published' FROM public.books WHERE slug = ${lit(row.slug)} ON CONFLICT (book_id) DO UPDATE SET quiz_data = EXCLUDED.quiz_data, flashcard_data = EXCLUDED.flashcard_data, status = EXCLUDED.status;`);
  }
  out.push('COMMIT;', '');
  return out.join('\n');
}

// ----- API mode -------------------------------------------------------------
async function api(method, url, key, body, prefer) {
  for (let attempt = 0; attempt < 4; attempt++) {
    const res = await fetch(url, {
      method,
      headers: { apikey: key, Authorization: `Bearer ${key}`, 'Content-Type': 'application/json', ...(prefer ? { Prefer: prefer } : {}) },
      body: body ? JSON.stringify(body) : undefined,
    });
    if (res.ok) { const t = await res.text(); return t ? JSON.parse(t) : null; }
    if (res.status >= 500 || res.status === 429) { await new Promise((r) => setTimeout(r, 1000 * 2 ** attempt)); continue; }
    throw new Error(`${method} ${url.split('?')[0]} -> ${res.status} ${await res.text()}`);
  }
  throw new Error(`${method} ${url.split('?')[0]} failed after retries`);
}

async function main() {
  const files = listBookFiles(dir);
  const items = [];
  const skipped = [];
  for (const f of files) {
    if (items.length >= limit) break;
    const r = toRow(f);
    if (r.error) skipped.push(`${path.basename(f)}: ${r.error}`); else items.push(r);
  }
  const dup = similarity(files);
  if (dup.length) { console.error('Refusing to upload: near-duplicate books detected:', dup); process.exit(1); }
  console.log(`${items.length} book(s) ready, ${skipped.length} skipped. Mode: ${publish ? 'PUBLISH' : 'draft'}${dry ? ' (dry run)' : ''}`);
  skipped.forEach((s) => console.log('  SKIPPED', s));
  if (!items.length) process.exit(skipped.length ? 1 : 0);

  if (sqlOut) {
    fs.writeFileSync(sqlOut, toSql(items));
    console.log(`Wrote ${sqlOut} (${(fs.statSync(sqlOut).size / 1024).toFixed(0)} KB). Paste it into Supabase > SQL Editor and run.`);
    return;
  }
  if (dry) { items.forEach((i) => console.log(`  would upsert ${i.row.slug} (${i.words} words)`)); return; }

  const base = (process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL || '').replace(/\/$/, '');
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!base || !key) { console.error('Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY (or use --sql).'); process.exit(1); }

  let done = 0;
  for (let i = 0; i < items.length; i += BATCH) {
    const chunk = items.slice(i, i + BATCH);
    const saved = await api('POST', `${base}/rest/v1/books?on_conflict=slug`, key, chunk.map((c) => c.row), 'resolution=merge-duplicates,return=representation');
    const idBySlug = Object.fromEntries(saved.map((b) => [b.slug, b.id]));
    await api('POST', `${base}/rest/v1/book_assets?on_conflict=book_id`, key, chunk.map((c) => ({ book_id: idBySlug[c.row.slug], ...c.assets })), 'resolution=merge-duplicates');
    done += chunk.length;
    console.log(`  uploaded ${done}/${items.length}`);
  }
  // Verify by reading back.
  const slugs = items.map((i) => i.row.slug);
  const back = await api('GET', `${base}/rest/v1/books?select=slug,language,is_draft&slug=in.(${slugs.join(',')})`, key);
  console.log(`Verified in Supabase: ${back.length}/${slugs.length} rows present.`);
  if (back.length !== slugs.length) process.exit(1);
}
main().catch((e) => { console.error(e.message); process.exit(1); });
