// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/search-books.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@2.105.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-books.ts
var search_books_default = defineTool({
  name: "search_books",
  title: "Search books",
  description: "Search Booknomics published book summaries by title, author, or category. Returns slug, title, author, category and language.",
  inputSchema: {
    query: z.string().trim().max(200).describe("Search text matched against book title and author."),
    language: z.enum(["en", "hi"]).optional().describe("Filter by language code."),
    category: z.string().trim().optional().describe("Filter by category name."),
    limit: z.number().int().optional().describe("Max results, default 10, max 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, language, category, limit }) => {
    const take = Math.min(Math.max(limit ?? 10, 1), 50);
    let q = supabaseAnon().from("books").select("slug,title,author,category,language,reading_time,rating").eq("is_draft", false).limit(take);
    const safeQuery = query.replace(/[^\p{L}\p{N}\s-]/gu, " ").trim();
    if (safeQuery) q = q.or(`title.ilike.%${safeQuery}%,author.ilike.%${safeQuery}%`);
    if (language) q = q.eq("language", language);
    if (category) q = q.ilike("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { books: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-book-summary.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^4.4.3";
var get_book_summary_default = defineTool2({
  name: "get_book_summary",
  title: "Get book summary",
  description: "Fetch the public summary content for one Booknomics book by its slug (overview and metadata). Premium sections (action system, trackers) require a paid subscription on booknomics.com and are not returned here.",
  inputSchema: {
    slug: z2.string().trim().describe("Book slug, e.g. 'atomic-habits'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const { data, error } = await supabaseAnon().from("books").select(
      "slug,title,author,category,language,reading_time,rating,tagline,overview,cover_url"
    ).eq("is_draft", false).eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No published book found for slug '${slug}'.` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { book: data }
    };
  }
});

// src/lib/mcp/tools/list-my-library.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_my_library_default = defineTool3({
  name: "list_my_library",
  title: "List my library",
  description: "List the books saved in the signed-in user's Booknomics library, with reading progress.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const [{ data: lib, error }, { data: progress }] = await Promise.all([
      supabase.from("library").select("book_id,created_at,books(slug,title,author,category,language)"),
      supabase.from("reading_progress").select("book_id,completed,last_read_at")
    ]);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const items = (lib ?? []).map((row) => ({
      ...row.books ?? {},
      saved_at: row.created_at,
      progress: (progress ?? []).find((p) => p.book_id === row.book_id) ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/tools/add-book-to-library.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^4.4.3";
var add_book_to_library_default = defineTool4({
  name: "add_book_to_library",
  title: "Add book to my library",
  description: "Save a published Booknomics book to the signed-in user's library, by book slug.",
  inputSchema: {
    slug: z3.string().trim().describe("Book slug to save, e.g. 'atomic-habits'.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: book, error: bookError } = await supabase.from("books").select("id,slug,title").eq("is_draft", false).eq("slug", slug).maybeSingle();
    if (bookError) return { content: [{ type: "text", text: bookError.message }], isError: true };
    if (!book) return { content: [{ type: "text", text: `No published book found for slug '${slug}'.` }], isError: true };
    const { error } = await supabase.from("library").upsert({ user_id: ctx.getUserId(), book_id: book.id }, { onConflict: "user_id,book_id", ignoreDuplicates: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved "${book.title}" to your library.` }],
      structuredContent: { saved: { slug: book.slug, title: book.title } }
    };
  }
});

// src/lib/mcp/tools/admin-update-book.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^4.4.3";
var admin_update_book_default = defineTool5({
  name: "admin_update_book",
  title: "Update book content (admin only)",
  description: "Update the specified public fields of one existing book. Requires an administrator role. Returns the saved fields. Does not change premium content, publication status, URLs, users, billing, code, or infrastructure.",
  inputSchema: {
    book_id: z4.string().uuid(),
    patch: z4.object({
      title: z4.string().trim().min(1).max(300).optional(),
      author: z4.string().trim().min(1).max(200).optional(),
      tagline: z4.string().trim().max(500).optional(),
      overview: z4.string().trim().max(2e4).optional(),
      category: z4.string().trim().min(1).max(100).optional(),
      meta_title: z4.string().trim().max(200).optional(),
      meta_description: z4.string().trim().max(500).optional()
    }).strict().refine((p) => Object.keys(p).length > 0, "Provide at least one field")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ book_id, patch }, ctx) => {
    const fail = (text) => ({ content: [{ type: "text", text }], isError: true });
    if (!ctx.isAuthenticated()) return fail("Authentication required");
    const db = supabaseForUser(ctx);
    const { data: allowed, error: roleError } = await db.rpc("has_role", { _user_id: ctx.getUserId(), _role: "admin" });
    if (roleError || allowed !== true) return fail("Administrator role required");
    const { data, error } = await db.from("books").update(patch).eq("id", book_id).select("id,title,author,tagline,overview,category,meta_title,meta_description").maybeSingle();
    if (error) return fail("Book update failed");
    if (!data) return fail("Book not found or access denied");
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { book: data } };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "book-insight-hub",
  title: "Book Insight Hub",
  version: "0.2.0",
  instructions: "Tools for Booknomics (Book Insight Hub), a library of AI-curated book summaries in English and Hindi. Use `search_books` to find books, `get_book_summary` to read a full summary, `list_my_library` to see the signed-in user's saved books and progress, and `add_book_to_library` to save a book for them. Admins can use admin_update_book to edit public book content. It does not edit website code or deployment settings.",
  auth: auth.oauth.issuer({
    issuer: `${supabaseProjectUrl()}/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_books_default, get_book_summary_default, list_my_library_default, add_book_to_library_default, admin_update_book_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
